@php($prefix = $gateway ? 'gateway_'.$gateway->id.'_' : 'gateway_new_')
<div class="row g-3">
  <div class="col-md-4"><label class="form-label">Name</label><input name="name" required maxlength="100" class="form-control" value="{{ $gateway?->name }}"></div>
  <div class="col-md-4"><label class="form-label">Slug</label><input name="slug" required maxlength="100" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" class="form-control" value="{{ $gateway?->slug }}" placeholder="bank-transfer"></div>
  <div class="col-md-4"><label class="form-label">Driver</label><select name="driver" class="form-select js-payment-driver" data-target="{{ $prefix }}">@foreach(['manual'=>'Manual transfer','stripe'=>'Stripe (configuration)','paypal'=>'PayPal (configuration)','custom'=>'Custom API (configuration)'] as $value=>$label)<option value="{{ $value }}" @selected(($gateway?->driver ?? 'manual') === $value)>{{ $label }}</option>@endforeach</select></div>
  <div class="col-md-6"><label class="form-label">Short description</label><textarea name="description" maxlength="2000" rows="3" class="form-control">{{ $gateway?->description }}</textarea></div>
  <div class="col-md-6"><label class="form-label">Customer instructions</label><textarea name="instructions" maxlength="10000" rows="3" class="form-control">{{ $gateway?->instructions }}</textarea></div>
  <div class="col-12 js-manual-fields" data-group="{{ $prefix }}"><label class="form-label">Payment / bank details shown to customer</label><textarea name="payment_details" maxlength="5000" rows="3" class="form-control">{{ data_get($gateway?->config, 'payment_details') }}</textarea></div>
  <div class="col-12 js-credential-fields" data-group="{{ $prefix }}"><div class="alert alert-secondary py-2 small">Secret fields are encrypted. Leave them blank while editing to preserve saved values.</div><div class="row g-3"><div class="col-md-3"><label class="form-label">Client / merchant ID</label><input name="client_id" autocomplete="off" class="form-control"></div><div class="col-md-3"><label class="form-label">API key</label><input type="password" name="api_key" autocomplete="new-password" class="form-control"></div><div class="col-md-3"><label class="form-label">API secret</label><input type="password" name="api_secret" autocomplete="new-password" class="form-control"></div><div class="col-md-3"><label class="form-label">Webhook secret</label><input type="password" name="webhook_secret" autocomplete="new-password" class="form-control"></div></div>@if($gateway && $gateway->driver !== 'manual' && $gateway->getRawOriginal('credentials'))<div class="form-text">Credentials are securely stored.</div>@endif</div>
  <div class="col-md-3"><label class="form-label">Fixed fee (base)</label><input type="number" min="0" step="0.00000001" name="fixed_fee" required class="form-control" value="{{ $gateway?->fixed_fee ?? '0' }}"></div>
  <div class="col-md-3"><label class="form-label">Percent fee</label><input type="number" min="0" max="100" step="0.0001" name="percent_fee" required class="form-control" value="{{ $gateway?->percent_fee ?? '0' }}"></div>
  <div class="col-md-3"><label class="form-label">Minimum (base)</label><input type="number" min="0.00000001" step="0.00000001" name="minimum_amount" class="form-control" value="{{ $gateway?->minimum_amount }}"></div>
  <div class="col-md-3"><label class="form-label">Maximum (base)</label><input type="number" min="0.00000001" step="0.00000001" name="maximum_amount" class="form-control" value="{{ $gateway?->maximum_amount }}"></div>
  <div class="col-md-8"><label class="form-label d-block">Supported currencies</label>@foreach($currencies as $currency)<div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="currency_ids[]" id="{{ $prefix }}currency{{ $currency->id }}" value="{{ $currency->id }}" @checked(!$gateway ? $currency->is_default : $gateway->currencies->contains($currency->id))><label class="form-check-label" for="{{ $prefix }}currency{{ $currency->id }}">{{ $currency->code }}</label></div>@endforeach</div>
  <div class="col-md-2"><label class="form-label">Ordering</label><input type="number" min="0" name="ordering" class="form-control" value="{{ $gateway?->ordering ?? 0 }}"></div>
  <div class="col-md-2"><label class="form-label">Logo</label><input type="file" name="logo" accept=".png,.jpg,.jpeg,.webp" class="form-control"></div>
  <div class="col-md-4"><input type="hidden" name="active" value="0"><div class="form-check form-switch"><input class="form-check-input" id="{{ $prefix }}active" type="checkbox" name="active" value="1" @checked($gateway?->active ?? false)><label class="form-check-label" for="{{ $prefix }}active">Active</label></div></div>
  <div class="col-md-4"><input type="hidden" name="sandbox" value="0"><div class="form-check form-switch"><input class="form-check-input" id="{{ $prefix }}sandbox" type="checkbox" name="sandbox" value="1" @checked($gateway?->sandbox ?? true)><label class="form-check-label" for="{{ $prefix }}sandbox">Sandbox mode</label></div></div>
</div>
@once @push('scripts')<script>function paymentDriverFields(select){const key=select.dataset.target;const manual=select.value==='manual';document.querySelectorAll(`[data-group="${key}"]`).forEach(el=>{if(el.classList.contains('js-manual-fields'))el.classList.toggle('d-none',!manual);if(el.classList.contains('js-credential-fields'))el.classList.toggle('d-none',manual);});}document.querySelectorAll('.js-payment-driver').forEach(el=>{paymentDriverFields(el);el.addEventListener('change',()=>paymentDriverFields(el));});</script>@endpush @endonce
