@extends('layouts.customer')
@section('title','Place order')
@section('content')
<div class="page-heading"><div><span class="eyebrow">FAST CHECKOUT</span><h1>Place a new order</h1><p>Select a category, choose the service and submit the required details.</p></div><div class="balance-chip"><span>Available balance</span><strong>${{ number_format((float)auth()->user()->balance,2) }}</strong></div></div>
<div class="order-type-tabs order-type-tabs-large mb-4">@foreach(['imei'=>['IMEI','mobile-screen-button'], 'server'=>['Server','server'], 'file'=>['File','file-arrow-up'], 'smm'=>['SMM','hashtag']] as $key=>$item)<a class="{{ $type===$key?'active':'' }}" href="{{ route('customer.orders.create',['type'=>$key]) }}"><i class="fas fa-{{ $item[1] }}"></i><span>{{ $item[0] }}</span><small>{{ ['imei'=>'IMEI / serial services','server'=>'Activations & credits','file'=>'Upload & processing','smm'=>'Social media services'][$key] }}</small></a>@endforeach</div>
<form id="orderForm" method="POST" enctype="multipart/form-data" action="{{ route('customer.orders.store',$type) }}">@csrf<input type="hidden" name="request_uid" value="{{ (string)Str::uuid() }}"><div class="row g-4"><div class="col-xl-8"><div class="gsm-card p-4"><div class="step-label"><span>1</span>Choose service</div><label class="form-label fw-bold">Service</label><select class="form-select form-select-lg" name="service_id" id="serviceSelect" required><option value="">Choose a service…</option>@foreach($catalog as $service)<option value="{{ $service['id'] }}">{{ $service['name'] }} — ${{ number_format($service['price'],2) }}</option>@endforeach</select><div id="serviceSummary" class="service-summary d-none"></div><div class="step-label mt-4"><span>2</span>Order details</div><div id="dynamicFields"><div class="empty-fields"><i class="fas fa-arrow-up"></i>Select a service to display its order form.</div></div><div class="mt-3"><label class="form-label fw-bold">Comments <span class="text-muted fw-normal">(optional)</span></label><textarea class="form-control" name="comments" rows="3" placeholder="Add any useful notes for the processing team"></textarea></div></div></div><div class="col-xl-4"><div class="gsm-card checkout-card"><div class="step-label"><span>3</span>Review & submit</div><div class="checkout-line"><span>Service price</span><strong id="summaryPrice">$0.00</strong></div><div class="checkout-line"><span>Category</span><strong>{{ strtoupper($type) }}</strong></div><div class="checkout-line total"><span>Total</span><strong id="summaryTotal">$0.00</strong></div><button class="btn btn-gsm btn-lg w-100" id="submitOrder" disabled>Place order securely <i class="fas fa-arrow-right ms-2"></i></button><p class="checkout-note"><i class="fas fa-shield-halved"></i>Your balance is charged once. Rejected eligible orders are refunded automatically.</p></div></div></div></form>
@push('scripts')<script>
const catalog=@json($catalog), type=@json($type), select=document.getElementById('serviceSelect'), fields=document.getElementById('dynamicFields'), summary=document.getElementById('serviceSummary'), button=document.getElementById('submitOrder');
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function inputFor(f){const name=`required[${escapeHtml(f.input)}]`,req=f.required?'required':'';if(['dropdown','select'].includes(f.type)){return `<select class="form-select" name="${name}" ${req}><option value="">Choose…</option>${f.options.map(o=>`<option value="${escapeHtml(typeof o==='object'?(o.value??o.name):o)}">${escapeHtml(typeof o==='object'?(o.label??o.name??o.value):o)}</option>`).join('')}</select>`}if(['textarea'].includes(f.type))return `<textarea class="form-control" rows="3" name="${name}" ${req}></textarea>`;return `<input class="form-control" type="${['email','number','url','password'].includes(f.type)?f.type:'text'}" name="${name}" ${f.minimum?`minlength="${f.minimum}"`:''} ${f.maximum?`maxlength="${f.maximum}"`:''} ${req}>`}
function render(){const s=catalog.find(x=>String(x.id)===select.value);button.disabled=!s;if(!s){fields.innerHTML='<div class="empty-fields"><i class="fas fa-arrow-up"></i>Select a service to display its order form.</div>';summary.classList.add('d-none');return}summary.classList.remove('d-none');summary.innerHTML=`<div><strong>${escapeHtml(s.name)}</strong><small>${escapeHtml(s.time||'Processing time shown by the service')}</small></div><strong>$${Number(s.price).toFixed(2)}</strong>${s.info?`<p>${escapeHtml(s.info)}</p>`:''}`;document.getElementById('summaryPrice').textContent=document.getElementById('summaryTotal').textContent='$'+Number(s.price).toFixed(2);let html='';if(type==='file')html+='<div class="mb-3"><label class="form-label fw-bold">Upload file</label><input class="form-control form-control-lg" type="file" name="file" required></div>';else html+=`<div class="mb-3"><label class="form-label fw-bold">${type==='smm'?'Link / username / target':'IMEI / serial / target'}</label><input class="form-control form-control-lg" name="device" ${type==='imei'?'required':''} placeholder="Enter the requested value"></div>`;if(type==='smm'||type==='server')html+='<div class="mb-3"><label class="form-label fw-bold">Quantity</label><input class="form-control" type="number" name="quantity" value="1" min="1" required></div>';if(s.allow_bulk&&type!=='file')html+='<div class="mb-3"><label class="form-label fw-bold">Bulk entries</label><textarea class="form-control" name="devices" rows="4" placeholder="One item per line"></textarea><input type="hidden" name="bulk" value="1"></div>';html+=s.fields.map(f=>`<div class="mb-3"><label class="form-label fw-bold">${escapeHtml(f.name)}${f.required?' *':''}</label>${inputFor(f)}${f.description?`<div class="form-text">${escapeHtml(f.description)}</div>`:''}</div>`).join('');fields.innerHTML=html}
select.addEventListener('change',render);if(@json((string)old('service_id',request('service')))){select.value=@json((string)old('service_id',request('service')));render()}
document.getElementById('orderForm').addEventListener('submit',async e=>{e.preventDefault();button.disabled=true;button.innerHTML='<i class="fas fa-spinner fa-spin me-2"></i>Submitting…';const r=await fetch(e.currentTarget.action,{method:'POST',body:new FormData(e.currentTarget),headers:{Accept:'application/json'}});const j=await r.json().catch(()=>({}));if(r.ok){location.href=@json(route('customer.orders.type',$type));return}button.disabled=false;button.innerHTML='Place order securely <i class="fas fa-arrow-right ms-2"></i>';alert(j.message||Object.values(j.errors||{}).flat().join('\n')||'The order could not be submitted.')});
</script>@endpush
@endsection
