@extends('layouts.customer')
@section('title',$type ? strtoupper($type).' orders' : 'My orders')
@section('content')
<div class="page-heading"><div><span class="eyebrow">ORDER CENTER</span><h1>{{ $type ? strtoupper($type).' orders' : 'All orders' }}</h1><p>Search, filter and follow every request from one clear workspace.</p></div><a class="btn btn-gsm btn-lg" href="{{ $type==='product'?route('site.store'):route('customer.orders.create',['type'=>$type ?: 'imei']) }}"><i class="fas fa-plus me-2"></i>Place order</a></div>
<div class="order-type-tabs mb-4">@foreach([''=>'All','imei'=>'IMEI','server'=>'Server','file'=>'File','smm'=>'SMM','product'=>'Products'] as $key=>$label)<a class="{{ ($type??'')===$key?'active':'' }}" href="{{ $key?route('customer.orders.type',$key):route('customer.orders') }}"><i class="fas fa-{{ [''=>'layer-group','imei'=>'mobile-screen','server'=>'server','file'=>'file-arrow-up','smm'=>'hashtag','product'=>'box'][$key] }}"></i>{{ $label }}</a>@endforeach</div>
<div class="gsm-card order-table-card"><div class="table-tools"><div class="input-group"><span class="input-group-text"><i class="fas fa-search"></i></span><input id="orderSearch" class="form-control" placeholder="Search by ID, service or device"></div><select id="statusFilter" class="form-select"><option value="">All statuses</option><option>waiting</option><option>inprogress</option><option>success</option><option>rejected</option><option>cancelled</option></select></div><div class="table-responsive"><table class="table align-middle mb-0" id="ordersTable"><thead><tr><th>Order</th><th>Service</th><th>Device / target</th><th>Status</th><th>Amount</th><th>Date</th><th></th></tr></thead><tbody>@forelse($orders as $order)<tr data-status="{{ strtolower($order['status']) }}"><td><strong>#{{ $order['id'] }}</strong><div class="small text-muted">{{ strtoupper($order['type']) }}</div></td><td class="fw-semibold">{{ $order['service'] }}</td><td>{{ str($order['device'])->limit(34) }}</td><td><span class="status-action status-{{ str($order['status'])->lower()->replace(' ','-') }}">{{ ucfirst($order['status']) }}</span></td><td>${{ number_format((float)$order['amount'],2) }}</td><td>{{ $order['created_at']?->format('Y-m-d H:i') }}</td><td><button type="button" class="btn btn-sm btn-view-order" data-url="{{ route('customer.orders.show',[$order['type'],$order['id']]) }}"><i class="fas fa-eye"></i> View</button></td></tr>@empty<tr><td colspan="7" class="empty-state"><i class="fas fa-box-open"></i><h4>No orders yet</h4><p>Choose a service and your first order will appear here.</p></td></tr>@endforelse</tbody></table></div></div>
<div class="modal fade" id="orderDetailsModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content order-modal"><div class="modal-header border-0"><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body pt-0" id="orderModalBody"><div class="modal-loading"><i class="fas fa-spinner fa-spin"></i> Loading order…</div></div></div></div></div>
@push('scripts')<script>const q=document.getElementById('orderSearch'),s=document.getElementById('statusFilter');function filterOrders(){document.querySelectorAll('#ordersTable tbody tr[data-status]').forEach(r=>r.hidden=!(r.innerText.toLowerCase().includes(q.value.toLowerCase())&&(!s.value||r.dataset.status===s.value)))}q?.addEventListener('input',filterOrders);s?.addEventListener('change',filterOrders);document.querySelectorAll('.btn-view-order').forEach(b=>b.addEventListener('click',async()=>{const body=document.getElementById('orderModalBody'),modal=window.bootstrap.Modal.getOrCreateInstance(document.getElementById('orderDetailsModal'));body.innerHTML='<div class="modal-loading"><i class="fas fa-spinner fa-spin"></i> Loading order…</div>';modal.show();try{const r=await fetch(b.dataset.url,{headers:{Accept:'application/json'}}),j=await r.json();body.innerHTML=r.ok?j.html:'<div class="alert alert-danger">Unable to load this order.</div>'}catch(e){body.innerHTML='<div class="alert alert-danger">Unable to load this order.</div>'}}))</script>@endpush
@endsection
