<?php
namespace Tests\Feature;
use App\Models\Download;use App\Models\DownloadCategory;use Illuminate\Database\Schema\Blueprint;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Schema;use Illuminate\Support\Facades\Storage;use Tests\Support\SecurityTestCase;
final class AdminDownloadsTest extends SecurityTestCase {
 protected function setUp():void{parent::setUp();Schema::create('groups',function(Blueprint $t){$t->id();$t->string('name');$t->timestamps();});(require database_path('migrations/2026_09_16_000600_create_downloads_tables.php'))->up();Storage::fake('local');}
 public function test_private_file_is_randomized_delivered_and_logged():void{$admin=$this->user('Administrator');$this->actingAs($admin);$category=DownloadCategory::create(['name'=>'Tools']);$this->post(route('admin.downloads.store'),['name'=>'Manual','download_category_id'=>$category->id,'source_type'=>'file','file'=>UploadedFile::fake()->create('guide.pdf',20,'application/pdf'),'active'=>'1','is_free'=>'1'])->assertRedirect();$download=Download::firstOrFail();$this->assertNotSame('guide.pdf',basename($download->storage_path));Storage::disk('local')->assertExists($download->storage_path);$this->get(route('admin.downloads.download',$download))->assertOk()->assertDownload('guide.pdf');$this->assertDatabaseHas('download_logs',['download_id'=>$download->id,'user_id'=>$admin->id]);$this->assertSame(1,$download->fresh()->download_count);}
 public function test_executable_upload_is_rejected():void{$this->actingAs($this->user('Administrator'));$this->post(route('admin.downloads.store'),['name'=>'Bad','source_type'=>'file','file'=>UploadedFile::fake()->create('payload.php',1,'application/x-php'),'active'=>'1','is_free'=>'1'])->assertSessionHasErrors('file');$this->assertDatabaseCount('downloads',0);}
 public function test_expired_download_is_not_delivered():void{$admin=$this->user('Administrator');$this->actingAs($admin);$expired=Download::create(['name'=>'Old','source_type'=>'external','external_url'=>'https://example.com/file','active'=>true,'is_free'=>true,'expires_at'=>now()->subMinute()]);$this->get(route('admin.downloads.download',$expired))->assertNotFound();}
 public function test_explicit_user_allowlist_is_enforced():void{$restricted=Download::create(['name'=>'Restricted','source_type'=>'external','external_url'=>'https://example.com/file','active'=>true,'is_free'=>true]);$allowed=$this->user();$restricted->users()->attach($allowed);$staff=$this->user();$staff->givePermissionTo(['admin.access','downloads.view']);$this->actingAs($staff);$this->get(route('admin.downloads.download',$restricted))->assertForbidden();}
 public function test_explicitly_allowed_user_can_download():void{$restricted=Download::create(['name'=>'Restricted','source_type'=>'external','external_url'=>'https://example.com/file','active'=>true,'is_free'=>true]);$allowed=$this->user();$allowed->givePermissionTo(['admin.access','downloads.view']);$restricted->users()->attach($allowed);$this->actingAs($allowed);$this->get(route('admin.downloads.download',$restricted))->assertRedirect('https://example.com/file');}
 public function test_view_permission_cannot_create_or_delete():void{$staff=$this->user();$staff->givePermissionTo(['admin.access','downloads.view']);$this->actingAs($staff);$this->get(route('admin.downloads.index'))->assertOk();$this->post(route('admin.downloads.store'),[])->assertForbidden();}
}
