@extends('layouts.admin')
@section('title', $t('admin.general.title','General settings'))
@section('content')
@php($v = fn($key, $default = '') => old($key, $settings['general.'.$key] ?? $default))
@php($emailVerification = old('email_verification_enabled', ($settings['general.email_verification_enabled'] ?? false) || (($settings['general.registration_activation'] ?? '') === 'email')))
@if(session('ok'))<div class="alert alert-success">{{ session('ok') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('admin.settings.general.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="row g-4"><div class="col-xl-6">
 <div class="card mb-4"><div class="card-header"><i class="fas fa-building me-1"></i> {{ $t('admin.general.site_information','Site information') }}</div><div class="card-body"><div class="row g-3">
  <div class="col-md-7"><label class="form-label">{{ $t('admin.general.site_name','Site name') }}</label><input name="site_name" class="form-control" required maxlength="120" value="{{ $v('site_name') }}"></div><div class="col-md-5"><label class="form-label">{{ $t('admin.general.tagline','Tagline') }}</label><input name="site_tagline" class="form-control" maxlength="255" value="{{ $v('site_tagline') }}"></div>
  <div class="col-md-6"><label class="form-label">{{ $t('admin.general.contact_email','Contact email') }}</label><input type="email" name="contact_email" class="form-control" value="{{ $v('contact_email') }}"></div><div class="col-md-6"><label class="form-label">{{ $t('admin.general.contact_phone','Contact phone') }}</label><input name="contact_phone" class="form-control" maxlength="50" value="{{ $v('contact_phone') }}"></div>
  <div class="col-12"><label class="form-label">{{ $t('admin.general.address','Address') }}</label><textarea name="contact_address" maxlength="500" rows="2" class="form-control">{{ $v('contact_address') }}</textarea></div><div class="col-md-6"><label class="form-label">{{ $t('admin.general.site_logo','Site logo') }}</label><input type="file" name="logo" class="form-control" accept=".png,.jpg,.jpeg,.webp">@if($v('logo'))<img class="mt-2 border rounded p-2 bg-dark" style="max-width:220px;max-height:80px" src="{{ asset('storage/'.$v('logo')) }}" alt="{{ $t('admin.general.current_logo','Current logo') }}">@endif</div><div class="col-md-6"><label class="form-label">{{ $t('admin.general.favicon','Favicon') }}</label><input type="file" name="favicon" class="form-control" accept="image/jpeg,image/png,image/webp">@if($v('favicon'))<img class="mt-2 border rounded p-1" style="width:48px;height:48px;object-fit:contain" src="{{ asset('storage/'.$v('favicon')) }}" alt="{{ $t('admin.general.current_favicon','Current favicon') }}">@endif</div>
 </div></div></div>
 <div class="card mb-4"><div class="card-header"><i class="fas fa-users-cog me-1"></i> {{ $t('admin.general.user_defaults','User defaults') }}</div><div class="card-body"><div class="row g-3">
  <div class="col-md-4"><label class="form-label">{{ $t('admin.general.registration_activation','Registration activation') }}</label><select name="registration_activation" class="form-select">@foreach(['automatic'=>$t('admin.general.automatic','Automatic'),'admin'=>$t('admin.general.admin_approval','Admin approval')] as $key=>$label)<option value="{{ $key }}" @selected(($v('registration_activation')==='email'?'automatic':$v('registration_activation'))===$key)>{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">{{ $t('admin.general.default_group','Default group') }}</label><select name="default_group_id" class="form-select"><option value="">{{ $t('admin.general.no_default','No default') }}</option>@foreach($groups as $group)<option value="{{ $group->id }}" @selected((string)$v('default_group_id')===(string)$group->id)>{{ $group->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">{{ $t('admin.general.default_overdraft','Default overdraft') }}</label><input type="number" min="0" step="0.00000001" name="default_overdraft" class="form-control" value="{{ $v('default_overdraft','0') }}"></div>
  <div class="col-md-6"><input type="hidden" name="email_verification_enabled" value="0"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="email_verification_enabled" name="email_verification_enabled" value="1" @checked($emailVerification)><label class="form-check-label" for="email_verification_enabled">{{ $t('admin.general.require_email_code','Require email verification code for new accounts') }}</label></div></div>
  @foreach(['registration_enabled'=>$t('admin.general.public_registration','Public registration'),'show_prices_to_guests'=>$t('admin.general.guest_prices','Show prices to guests'),'show_original_prices'=>$t('admin.general.original_prices','Show original prices'),'allow_credit_transfers'=>$t('admin.general.credit_transfers','Allow credit transfers')] as $key=>$label)<div class="col-md-6"><input type="hidden" name="{{ $key }}" value="0"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="{{ $key }}" name="{{ $key }}" value="1" @checked($v($key))><label class="form-check-label" for="{{ $key }}">{{ $label }}</label></div></div>@endforeach
 </div></div></div>
</div><div class="col-xl-6">
 <div class="card mb-4"><div class="card-header"><i class="fas fa-shield-halved me-1"></i> {{ $t('admin.general.signin_security','Sign-in security') }}</div><div class="card-body"><p class="text-muted">{{ $t('admin.general.signin_help','Configure mandatory email verification and Google sign-in in a protected dialog.') }}</p><button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#signInSecurityModal"><i class="fas fa-lock me-1"></i> {{ $t('admin.general.configure_signin','Configure sign-in security') }}</button></div></div>
 <div class="card mb-4"><div class="card-header"><i class="fas fa-clock me-1"></i> {{ $t('admin.general.locale_session','Locale and session') }}</div><div class="card-body"><div class="row g-3">
  <div class="col-md-6"><label class="form-label">{{ $t('admin.general.timezone','Timezone') }}</label><select name="timezone" class="form-select">@foreach(timezone_identifiers_list() as $timezone)<option value="{{ $timezone }}" @selected($v('timezone')===$timezone)>{{ $timezone }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">{{ $t('admin.general.date_format','Date format') }}</label><select name="date_format" class="form-select">@foreach(['Y-m-d','d/m/Y','m/d/Y','d M Y'] as $format)<option value="{{ $format }}" @selected($v('date_format')===$format)>{{ now()->format($format) }} ({{ $format }})</option>@endforeach</select></div>
  <div class="col-md-6"><label class="form-label">{{ $t('admin.general.session_lifetime','Session lifetime (minutes)') }}</label><input type="number" min="5" max="43200" name="session_lifetime" class="form-control" value="{{ $v('session_lifetime',120) }}"></div><div class="col-md-6 d-flex align-items-end"><input type="hidden" name="session_expire_on_close" value="0"><div class="form-check form-switch mb-2"><input class="form-check-input" id="session_expire_on_close" type="checkbox" name="session_expire_on_close" value="1" @checked($v('session_expire_on_close'))><label class="form-check-label" for="session_expire_on_close">{{ $t('admin.general.expire_on_close','Expire when browser closes') }}</label></div></div>
  <div class="col-12"><label class="form-label">{{ $t('admin.general.low_balance','API low-balance warning threshold') }}</label><div class="input-group"><input type="number" min="0" step="0.00000001" name="api_low_balance_threshold" class="form-control" value="{{ $v('api_low_balance_threshold','0') }}"><span class="input-group-text">{{ $t('admin.general.credits','Credits') }}</span></div></div>
 </div></div></div>
 <div class="card"><div class="card-header"><i class="fas fa-search me-1"></i> {{ $t('admin.general.search_metadata','Search metadata') }}</div><div class="card-body"><div class="row g-3"><div class="col-12"><label class="form-label">{{ $t('admin.general.meta_title','Meta title') }}</label><input name="meta_title" maxlength="70" class="form-control" value="{{ $v('meta_title') }}"></div><div class="col-12"><label class="form-label">{{ $t('admin.general.meta_description','Meta description') }}</label><textarea name="meta_description" maxlength="170" rows="3" class="form-control">{{ $v('meta_description') }}</textarea></div><div class="col-12"><label class="form-label">{{ $t('admin.general.keywords','Keywords') }}</label><input name="meta_keywords" maxlength="500" class="form-control" value="{{ $v('meta_keywords') }}"><div class="form-text">{{ $t('admin.general.keywords_help','Comma-separated. Arbitrary code injection is intentionally not allowed.') }}</div></div></div></div></div>
</div></div>
<div class="modal fade" id="signInSecurityModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><h2 class="modal-title h5 mb-0">{{ $t('admin.general.signin_security','Sign-in security') }}</h2><div class="small text-muted">{{ $t('admin.general.signin_subtitle','Email two-step verification and Google OAuth') }}</div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-12"><input type="hidden" name="two_factor_enabled" value="0"><div class="form-check form-switch"><input class="form-check-input" id="two_factor_enabled" type="checkbox" name="two_factor_enabled" value="1" @checked($v('two_factor_enabled'))><label class="form-check-label fw-bold" for="two_factor_enabled">{{ $t('admin.general.require_two_factor','Require email two-step verification for every user') }}</label><div class="form-text">{{ $t('admin.general.two_factor_help','When disabled, customers may still enable it individually. When enabled, no customer can bypass it.') }}</div></div></div>
<div class="col-12"><hr></div><div class="col-12"><input type="hidden" name="google_login_enabled" value="0"><div class="form-check form-switch"><input class="form-check-input" id="google_login_enabled" type="checkbox" name="google_login_enabled" value="1" @checked($v('google_login_enabled'))><label class="form-check-label fw-bold" for="google_login_enabled">{{ $t('admin.general.enable_google','Enable Google sign-in') }}</label></div></div>
<div class="col-12"><label class="form-label">{{ $t('admin.general.google_client_id','Google OAuth Client ID') }}</label><input name="google_client_id" class="form-control" value="{{ old('google_client_id',$settings['auth.google_client_id'] ?? '') }}" autocomplete="off"></div>
<div class="col-12"><label class="form-label">{{ $t('admin.general.google_secret','Google OAuth Secret Code') }}</label><input type="password" name="google_client_secret" class="form-control" autocomplete="new-password" placeholder="{{ $googleSecretConfigured?$t('admin.general.keep_secret','Leave blank to keep saved secret'):$t('admin.general.enter_secret','Enter secret code') }}"><div class="form-text">{{ $t('admin.general.redirect_uri','Authorized redirect URI:') }} <code>{{ route('auth.google.callback') }}</code></div></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ $t('common.close','Close') }}</button><button class="btn btn-primary"><i class="fas fa-save me-1"></i> {{ $t('admin.general.save_security','Save security settings') }}</button></div></div></div></div>
<div class="sticky-bottom bg-white border-top mt-4 py-3 text-end"><button class="btn btn-primary px-4"><i class="fas fa-save me-1"></i> {{ $t('admin.general.save_all','Save all settings') }}</button></div></form>
@endsection
