@extends('layouts.admin')
@section('title',$invoice->number)
@section('content')
<div class="card"><div class="card-header bg-primary text-white d-flex justify-content-between"><strong>{{ $invoice->number }}</strong><span><a class="btn btn-light btn-sm" target="_blank" href="{{ route('admin.finances.invoices.print',$invoice) }}">Print</a> @if(in_array($invoice->status,['draft','pending']))<a class="btn btn-warning btn-sm" href="{{ route('admin.finances.invoices.edit',$invoice) }}">Edit</a>@endif</span></div><div class="card-body">
@if(session('ok'))<div class="alert alert-success">{{ session('ok') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row"><div class="col-md-6"><h5>Customer</h5><p>{{ data_get($invoice->customer_snapshot,'name') }}<br>{{ data_get($invoice->customer_snapshot,'email') }}</p></div><div class="col-md-6 text-md-end"><p>Status: <strong>{{ $invoice->status }}</strong><br>Issued: {{ $invoice->issued_at?->format('Y-m-d')??'—' }}<br>Due: {{ $invoice->due_at?->format('Y-m-d')??'—' }}</p></div></div>
<table class="table"><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Discount</th><th>Tax</th><th>Total</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->quantity }}</td><td>{{ $item->unit_price }}</td><td>{{ $item->discount }}</td><td>{{ $item->tax_rate }}%</td><td>{{ $item->line_total }}</td></tr>@endforeach</tbody></table>
<div class="text-end"><p>Subtotal: {{ $invoice->subtotal }}<br>Tax: {{ $invoice->tax_total }}<br>Discount: {{ $invoice->discount_total }}<br>Fees: {{ $invoice->fee_total }}</p><h4>Total: {{ $invoice->total }} {{ $invoice->currency_code }}</h4><p>Paid: {{ $invoice->paid_total }} · Due: {{ $invoice->balance_due }}</p></div>
@if($invoice->notes)<h6>Notes</h6><p>{{ $invoice->notes }}</p>@endif @if($invoice->terms)<h6>Terms</h6><p>{{ $invoice->terms }}</p>@endif
@if(in_array($invoice->status,['pending','partially_paid']) && bccomp((string)$invoice->balance_due,'0',4)>0)<hr><h5>Record verified payment</h5><form method="POST" action="{{ route('admin.finances.invoices.payments.store',$invoice) }}" class="row g-2">@csrf<div class="col-md-3"><input class="form-control" name="amount" placeholder="Amount" required></div><div class="col-md-4"><input class="form-control" name="reference" placeholder="Gateway/bank reference" required></div><div class="col-md-3"><input class="form-control" type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></div><div class="col"><button class="btn btn-success">Record</button></div></form>@endif
@if($invoice->payments->isNotEmpty())<h5 class="mt-4">Payments</h5><table class="table table-sm"><thead><tr><th>Date</th><th>Reference</th><th>Amount</th></tr></thead><tbody>@foreach($invoice->payments as $payment)<tr><td>{{ $payment->paid_at }}</td><td>{{ $payment->reference }}</td><td>{{ $payment->amount }} {{ $payment->currency_code }}</td></tr>@endforeach</tbody></table>@endif
@if(in_array($invoice->status,['draft','pending']))<div class="d-flex gap-2 mt-4">@if($invoice->status==='draft')<form method="POST" action="{{ route('admin.finances.invoices.destroy',$invoice) }}" onsubmit="return confirm('Delete this draft?')">@csrf @method('DELETE')<button class="btn btn-danger">Delete draft</button></form>@endif<form method="POST" action="{{ route('admin.finances.invoices.cancel',$invoice) }}" onsubmit="return confirm('Cancel this invoice?')">@csrf<button class="btn btn-outline-danger">Cancel invoice</button></form></div>@endif
</div></div>
@endsection
