@extends('layouts.admin')
@section('title','Media manager')
@section('content')
<div class="admin-page-head"><div><span class="admin-kicker">ADMIN MEDIA</span><h1>Image manager</h1><p>Logos, banners, products, pages and every image uploaded by administrators. Customer payment proofs are excluded.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#mediaUpload"><i class="fas fa-plus me-1"></i> Upload image</button></div>
@if(session('ok'))<div class="alert alert-success">{{ session('ok') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="media-toolbar"><input class="form-control" id="mediaSearch" placeholder="Search filename or folder"><span>{{ $files->count() }} images</span></div>
<div class="media-grid" id="mediaGrid">@forelse($files as $file)<article class="media-tile" data-search="{{ strtolower($file['name'].' '.$file['folder']) }}"><a href="{{ $file['url'] }}" target="_blank"><img src="{{ $file['url'] }}" alt="{{ $file['name'] }}" loading="lazy"></a><div><strong title="{{ $file['name'] }}">{{ $file['name'] }}</strong><span>{{ $file['folder'] }} · {{ number_format($file['size']/1024,1) }} KB</span></div><div class="media-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.system.filemanager.download',$file['name']) }}"><i class="fas fa-download"></i></a>@if($file['managed'])<form method="POST" action="{{ route('admin.system.filemanager.destroy',$file['name']) }}" onsubmit="return confirm('Delete this uploaded media image?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fas fa-trash"></i></button></form>@endif</div></article>@empty<div class="empty-state">No administrator images found.</div>@endforelse</div>
<div class="modal fade" id="mediaUpload" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" enctype="multipart/form-data">@csrf<div class="modal-header"><h2 class="modal-title h5">Upload admin image</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><input class="form-control" type="file" name="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif" required><div class="form-text">Only safe raster images, maximum 10 MB.</div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Upload</button></div></form></div></div>
@push('scripts')<script>document.getElementById('mediaSearch')?.addEventListener('input',e=>document.querySelectorAll('.media-tile').forEach(tile=>tile.hidden=!tile.dataset.search.includes(e.target.value.toLowerCase())));</script>@endpush
@endsection
