@extends('layouts.admin')
@section('title','Customer maintenance mode')
@section('content')
<div class="admin-page-head"><div><span class="admin-kicker">SYSTEM CONTROL</span><h1>Customer maintenance page</h1><p>Pause the customer-facing website while administrators continue working normally.</p></div><span class="status-dot {{ $enabled?'is-inactive':'is-active' }}">{{ $enabled?'Customers paused':'Website online' }}</span></div>
@if(session('ok'))<div class="alert alert-success">{{ session('ok') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" enctype="multipart/form-data">@csrf @method('PUT')<div class="row g-4"><div class="col-xl-7"><div class="card admin-panel"><div class="card-body p-4">
<input type="hidden" name="enabled" value="0"><div class="form-check form-switch maintenance-switch"><input class="form-check-input" id="maintenanceEnabled" type="checkbox" name="enabled" value="1" @checked($enabled)><label class="form-check-label" for="maintenanceEnabled"><strong>Enable maintenance mode</strong><span>Customers receive a 503 maintenance page; administrators remain online.</span></label></div><hr>
<label class="form-label fw-bold">Customer message</label><textarea class="form-control" name="message" rows="8" placeholder="We are performing scheduled maintenance...">{{ old('message',$message) }}</textarea>
<label class="form-label fw-bold mt-4">Maintenance image</label><input class="form-control" type="file" name="image" accept="image/jpeg,image/png,image/webp,image/gif,image/avif"><div class="form-text">JPG, PNG, WEBP, GIF or AVIF — maximum 10 MB.</div>
@if($image)<div class="maintenance-current mt-3"><img src="{{ Storage::disk('public')->url($image) }}" alt="Current maintenance image"><label><input type="checkbox" name="remove_image" value="1"> Remove current image</label></div>@endif
<button class="btn btn-primary mt-4"><i class="fas fa-floppy-disk me-2"></i>Save maintenance page</button></div></div></div><div class="col-xl-5"><div class="card admin-panel"><div class="panel-title"><h2>Customer preview</h2></div><div class="maintenance-preview">@if($image)<img src="{{ Storage::disk('public')->url($image) }}" alt="Preview">@else<div class="maintenance-preview-icon"><i class="fas fa-screwdriver-wrench"></i></div>@endif<h2>We’ll be back soon</h2><p>{{ $message ?: 'We are currently performing scheduled maintenance. Please check back soon.' }}</p></div></div></div></div></form>
@endsection
