import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('download edit embeds raw JSON that the button handler can parse',()=>{const view=readFileSync('resources/views/admin/downloads/index.blade.php','utf8');assert.match(view,/json_encode\(\$downloadEditData/);assert.match(view,/JSON\.parse\(document\.getElementById/);assert.doesNotMatch(view,/Js::from\(\['name'=>\$d->name/)});
test('latest products reserve compact artwork and visible details',()=>{const css=readFileSync('resources/css/app.css','utf8');assert.match(css,/grid-template-rows:150px 1fr/);assert.match(css,/\.cyber-product \.product-visual\{height:150px/)});
test('admin dashboard exposes the live command center metrics',()=>{const view=readFileSync('resources/views/admin/dashboard.blade.php','utf8');for(const label of ['Today Orders','Today Registrations','Today Payments','Today Profit','Online Users','Order Acceptance Rate','Order Rejection Rate','Pending Approval','Payment Review Alerts','Recent Orders','Live Activity'])assert.match(view,new RegExp(label));assert.match(view,/data-refresh-seconds="60"/);assert.match(view,/window\.location\.reload\(\)/)});
test('general settings omits social links and module switches',()=>{const view=readFileSync('resources/views/admin/settings/general.blade.php','utf8');assert.doesNotMatch(view,/Social links/);assert.doesNotMatch(view,/Modules and display/)});
test('access logs provide managed IP blocking',()=>{const view=readFileSync('resources/views/admin/logs/access.blade.php','utf8');const middleware=readFileSync('app/Http/Middleware/RejectBlockedIp.php','utf8');assert.match(view,/Block IP/);assert.match(view,/Unblock/);assert.match(middleware,/blocked_ips/)});
test('admin color mode toggle is available and persistent',()=>{const navbar=readFileSync('resources/views/partials/navbar.blade.php','utf8');const layout=readFileSync('resources/views/layouts/admin.blade.php','utf8');const js=readFileSync('resources/js/admin.js','utf8');const css=readFileSync('resources/css/admin.css','utf8');assert.match(navbar,/id="adminThemeToggle"/);assert.match(layout,/localStorage\.getItem\('admin-theme'\)/);assert.match(js,/localStorage\.setItem\('admin-theme'/);assert.match(css,/data-admin-theme="light"/)});

test('general settings is localized across all supported admin languages',()=>{const view=readFileSync('resources/views/admin/settings/general.blade.php','utf8');const migration=readFileSync('database/migrations/2026_09_18_000400_seed_general_settings_translations.php','utf8');for(const key of ['admin.general.site_information','admin.general.user_defaults','admin.general.signin_security','admin.general.locale_session','admin.general.search_metadata','admin.general.save_all','admin.general.saved'])assert.ok((view+migration).includes(key));for(const locale of ["'ar'=>","'fr'=>","'es'=>","'de'=>","'tr'=>"])assert.ok(migration.includes(locale));});
