import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';

test('page manager protects core pages and opens real previews',()=>{const controller=readFileSync('app/Http/Controllers/Admin/PageController.php','utf8'),index=readFileSync('resources/views/admin/pages/index.blade.php','utf8'),form=readFileSync('resources/views/admin/pages/form.blade.php','utf8');assert.match(controller,/if\(\$page->system\)/);assert.match(controller,/return redirect\(\)->to\(route\(\$route\)/);assert.match(index,/@unless\(\$page->system\)/);assert.match(index,/target="_blank"/);assert.match(form,/Protected core page/);assert.match(form,/Page appearance override/)});
test('theme studio supports saved activation preview and constrained controls',()=>{const theme=readFileSync('app/Http/Controllers/Admin/PageThemeController.php','utf8'),view=readFileSync('resources/views/admin/pages/theme.blade.php','utf8'),layout=readFileSync('resources/views/layouts/site.blade.php','utf8'),provider=readFileSync('app/Providers/AppServiceProvider.php','utf8');assert.match(theme,/PageTheme::query\(\)->update\(\['active'=>false\]\)/);assert.match(theme,/between:13,20/);assert.match(view,/Live preview/);assert.match(view,/theme-control/);assert.match(layout,/--page-primary/);assert.match(provider,/theme_preview/)});

test('original theme can be restored without deleting saved themes',()=>{const controller=readFileSync('app/Http/Controllers/Admin/PageThemeController.php','utf8'),pages=readFileSync('app/Http/Controllers/Admin/PageController.php','utf8'),index=readFileSync('resources/views/admin/pages/index.blade.php','utf8');assert.match(controller,/restoreOriginal/);assert.match(controller,/where\('active',true\)->update\(\['active'=>false\]\)/);assert.match(pages,/originalThemeActive/);assert.match(index,/Restore original theme/);assert.match(index,/saved themes.*not be deleted/i)});
test('page management uses branded confirmation and a real menu tree customizer',()=>{const index=readFileSync('resources/views/admin/pages/index.blade.php','utf8'),layout=readFileSync('resources/views/layouts/site.blade.php','utf8'),controller=readFileSync('app/Http/Controllers/Admin/MenuController.php','utf8'),migration=readFileSync('database/migrations/2026_09_19_000300_seed_default_header_menu.php','utf8');assert.doesNotMatch(index,/onsubmit="return confirm/);assert.match(index,/siteConfirmModal/);assert.match(index,/Customize main menu/);assert.match(index,/Visible menu tree/);assert.match(index,/Available pages/);assert.match(index,/dragstart/);assert.match(controller,/Circular menu branches are not allowed/);assert.match(layout,/_site-menu-tree/);assert.match(migration,/header-primary/)});
test('privacy and terms expose safe rich content while page chrome stays fixed',()=>{const controller=readFileSync('app/Http/Controllers/Admin/PageController.php','utf8'),form=readFileSync('resources/views/admin/pages/form.blade.php','utf8'),page=readFileSync('resources/views/site/page.blade.php','utf8');assert.match(controller,/CONTENT_EDITABLE_SYSTEM_PAGES = \['privacy', 'terms'\]/);assert.match(form,/page-content-editor/);assert.match(form,/codeview/);assert.match(form,/Content, SEO, visibility and access/);assert.match(page,/@extends\('layouts.site'\)/)});
