<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        if (! Schema::hasTable('languages') || ! Schema::hasTable('language_translations')) return;

        $sets = [
            'ar' => [
                'admin.nav.dashboard'=>'لوحة القيادة','admin.nav.user_management'=>'إدارة المستخدمين','admin.nav.users'=>'المستخدمون','admin.nav.groups'=>'المجموعات','admin.nav.roles'=>'الأدوار','admin.nav.permissions'=>'الصلاحيات','admin.nav.order_management'=>'إدارة الطلبات','admin.nav.imei_orders'=>'طلبات IMEI','admin.nav.server_orders'=>'طلبات السيرفر','admin.nav.file_orders'=>'طلبات الملفات','admin.nav.smm_orders'=>'طلبات SMM','admin.nav.product_orders'=>'طلبات المنتجات','admin.nav.service_management'=>'إدارة الخدمات','admin.nav.service_groups'=>'مجموعات الخدمات','admin.nav.imei_services'=>'خدمات IMEI','admin.nav.server_services'=>'خدمات السيرفر','admin.nav.file_services'=>'خدمات الملفات','admin.nav.smm_services'=>'خدمات SMM','admin.nav.retail_store'=>'متجر التجزئة','admin.nav.product_categories'=>'تصنيفات المنتجات','admin.nav.products'=>'المنتجات','admin.nav.local_sources'=>'المصادر المحلية','admin.nav.sources'=>'المصادر','admin.nav.replies'=>'الردود','admin.nav.downloads'=>'التنزيلات','admin.nav.download_categories'=>'تصنيفات التنزيل','admin.nav.finances'=>'المالية','admin.nav.invoices'=>'الفواتير','admin.nav.payment_reviews'=>'مراجعة المدفوعات','admin.nav.statements'=>'كشوف الحساب','admin.nav.transactions'=>'المعاملات','admin.nav.api_management'=>'إدارة API','admin.nav.settings'=>'الإعدادات','admin.nav.general_settings'=>'الإعدادات العامة','admin.nav.home_banners'=>'لافتات الرئيسية','admin.nav.resellers'=>'موزعو الشحن','admin.nav.mail_settings'=>'إعدادات البريد','admin.nav.payment_settings'=>'إعدادات الدفع','admin.nav.languages'=>'اللغات','admin.nav.currencies'=>'العملات','admin.nav.page_management'=>'إدارة الصفحات','admin.nav.system'=>'النظام','admin.nav.file_manager'=>'مدير الملفات','admin.nav.update'=>'التحديث','admin.nav.maintenance'=>'وضع الصيانة','admin.nav.backups'=>'النسخ الاحتياطية','admin.nav.reports'=>'التقارير','admin.nav.user_reports'=>'تقارير المستخدمين','admin.nav.service_reports'=>'تقارير الخدمات','admin.nav.product_reports'=>'تقارير المنتجات','admin.nav.logs'=>'السجلات','admin.nav.access_logs'=>'سجلات الدخول','admin.nav.activity_logs'=>'سجلات النشاط','admin.nav.error_logs'=>'سجلات الأخطاء',
                'admin.menu.profile'=>'ملفي الشخصي','admin.menu.password'=>'تغيير كلمة المرور','admin.menu.general_settings'=>'الإعدادات العامة','admin.menu.security'=>'الأمان','admin.menu.manage_languages'=>'إدارة اللغات','admin.account.kicker'=>'الحساب والأمان','admin.account.title'=>'حساب المسؤول','admin.account.subtitle'=>'إدارة هوية المسؤول وكلمة المرور وحالة الأمان.','admin.account.identity'=>'هوية المسؤول','admin.account.updated'=>'تم تحديث الحساب.','admin.password.title'=>'تغيير كلمة المرور','admin.password.help'=>'استخدم 12 حرفًا على الأقل. سيؤدي تغيير كلمة المرور إلى تجديد الجلسة الآمنة.','admin.password.current'=>'كلمة المرور الحالية','admin.password.new'=>'كلمة المرور الجديدة','admin.password.confirm'=>'تأكيد كلمة المرور الجديدة','admin.password.update'=>'تحديث كلمة المرور','admin.password.updated'=>'تم تحديث كلمة المرور بأمان.','admin.security.title'=>'حالة الأمان','admin.security.role'=>'دور المسؤول','admin.security.email'=>'التحقق من البريد','admin.security.two_factor'=>'التحقق بخطوتين','admin.security.last_update'=>'آخر تحديث للحساب','admin.security.access_logs'=>'مراجعة سجلات الدخول','common.full_name'=>'الاسم الكامل','common.username'=>'اسم المستخدم','common.email'=>'البريد الإلكتروني','common.save_changes'=>'حفظ التغييرات','common.active'=>'نشط','common.verified'=>'موثّق','common.pending'=>'قيد الانتظار','common.enabled'=>'مفعّل','common.disabled'=>'معطّل',
            ],
            'fr' => [
                'admin.nav.dashboard'=>'Tableau de bord','admin.nav.user_management'=>'Gestion des utilisateurs','admin.nav.users'=>'Utilisateurs','admin.nav.groups'=>'Groupes','admin.nav.roles'=>'Rôles','admin.nav.permissions'=>'Autorisations','admin.nav.order_management'=>'Gestion des commandes','admin.nav.imei_orders'=>'Commandes IMEI','admin.nav.server_orders'=>'Commandes serveur','admin.nav.file_orders'=>'Commandes fichiers','admin.nav.smm_orders'=>'Commandes SMM','admin.nav.product_orders'=>'Commandes produits','admin.nav.service_management'=>'Gestion des services','admin.nav.service_groups'=>'Groupes de services','admin.nav.imei_services'=>'Services IMEI','admin.nav.server_services'=>'Services serveur','admin.nav.file_services'=>'Services fichiers','admin.nav.smm_services'=>'Services SMM','admin.nav.retail_store'=>'Boutique','admin.nav.product_categories'=>'Catégories de produits','admin.nav.products'=>'Produits','admin.nav.local_sources'=>'Sources locales','admin.nav.sources'=>'Sources','admin.nav.replies'=>'Réponses','admin.nav.downloads'=>'Téléchargements','admin.nav.download_categories'=>'Catégories de téléchargement','admin.nav.finances'=>'Finances','admin.nav.invoices'=>'Factures','admin.nav.payment_reviews'=>'Vérification des paiements','admin.nav.statements'=>'Relevés','admin.nav.transactions'=>'Transactions','admin.nav.api_management'=>'Gestion API','admin.nav.settings'=>'Paramètres','admin.nav.general_settings'=>'Paramètres généraux','admin.nav.home_banners'=>'Bannières d’accueil','admin.nav.resellers'=>'Revendeurs de recharge','admin.nav.mail_settings'=>'Paramètres e-mail','admin.nav.payment_settings'=>'Paramètres de paiement','admin.nav.languages'=>'Langues','admin.nav.currencies'=>'Devises','admin.nav.page_management'=>'Gestion des pages','admin.nav.system'=>'Système','admin.nav.file_manager'=>'Gestionnaire de fichiers','admin.nav.update'=>'Mise à jour','admin.nav.maintenance'=>'Mode maintenance','admin.nav.backups'=>'Sauvegardes','admin.nav.reports'=>'Rapports','admin.nav.user_reports'=>'Rapports utilisateurs','admin.nav.service_reports'=>'Rapports services','admin.nav.product_reports'=>'Rapports produits','admin.nav.logs'=>'Journaux','admin.nav.access_logs'=>'Journaux d’accès','admin.nav.activity_logs'=>'Journaux d’activité','admin.nav.error_logs'=>'Journaux d’erreurs',
                'admin.menu.profile'=>'Mon profil','admin.menu.password'=>'Changer le mot de passe','admin.menu.general_settings'=>'Paramètres généraux','admin.menu.security'=>'Sécurité','admin.menu.manage_languages'=>'Gérer les langues','admin.account.kicker'=>'COMPTE ET SÉCURITÉ','admin.account.title'=>'Compte administrateur','admin.account.subtitle'=>'Gérez votre identité, votre mot de passe et votre sécurité.','admin.account.identity'=>'Identité administrateur','admin.account.updated'=>'Compte mis à jour.','admin.password.title'=>'Changer le mot de passe','admin.password.help'=>'Utilisez au moins 12 caractères. Le changement renouvelle votre session sécurisée.','admin.password.current'=>'Mot de passe actuel','admin.password.new'=>'Nouveau mot de passe','admin.password.confirm'=>'Confirmer le mot de passe','admin.password.update'=>'Mettre à jour le mot de passe','admin.password.updated'=>'Mot de passe mis à jour en toute sécurité.','admin.security.title'=>'État de sécurité','admin.security.role'=>'Rôle administrateur','admin.security.email'=>'Vérification e-mail','admin.security.two_factor'=>'Authentification à deux facteurs','admin.security.last_update'=>'Compte mis à jour','admin.security.access_logs'=>'Consulter les journaux d’accès','common.full_name'=>'Nom complet','common.username'=>'Nom d’utilisateur','common.email'=>'Adresse e-mail','common.save_changes'=>'Enregistrer','common.active'=>'Actif','common.verified'=>'Vérifié','common.pending'=>'En attente','common.enabled'=>'Activé','common.disabled'=>'Désactivé',
            ],
            'es' => [
                'admin.nav.dashboard'=>'Panel de control','admin.nav.user_management'=>'Gestión de usuarios','admin.nav.users'=>'Usuarios','admin.nav.groups'=>'Grupos','admin.nav.roles'=>'Roles','admin.nav.permissions'=>'Permisos','admin.nav.order_management'=>'Gestión de pedidos','admin.nav.imei_orders'=>'Pedidos IMEI','admin.nav.server_orders'=>'Pedidos de servidor','admin.nav.file_orders'=>'Pedidos de archivos','admin.nav.smm_orders'=>'Pedidos SMM','admin.nav.product_orders'=>'Pedidos de productos','admin.nav.service_management'=>'Gestión de servicios','admin.nav.service_groups'=>'Grupos de servicios','admin.nav.imei_services'=>'Servicios IMEI','admin.nav.server_services'=>'Servicios de servidor','admin.nav.file_services'=>'Servicios de archivos','admin.nav.smm_services'=>'Servicios SMM','admin.nav.retail_store'=>'Tienda','admin.nav.product_categories'=>'Categorías de productos','admin.nav.products'=>'Productos','admin.nav.local_sources'=>'Fuentes locales','admin.nav.sources'=>'Fuentes','admin.nav.replies'=>'Respuestas','admin.nav.downloads'=>'Descargas','admin.nav.download_categories'=>'Categorías de descarga','admin.nav.finances'=>'Finanzas','admin.nav.invoices'=>'Facturas','admin.nav.payment_reviews'=>'Revisión de pagos','admin.nav.statements'=>'Estados de cuenta','admin.nav.transactions'=>'Transacciones','admin.nav.api_management'=>'Gestión de API','admin.nav.settings'=>'Ajustes','admin.nav.general_settings'=>'Ajustes generales','admin.nav.home_banners'=>'Banners de inicio','admin.nav.resellers'=>'Distribuidores de recarga','admin.nav.mail_settings'=>'Ajustes de correo','admin.nav.payment_settings'=>'Ajustes de pago','admin.nav.languages'=>'Idiomas','admin.nav.currencies'=>'Monedas','admin.nav.page_management'=>'Gestión de páginas','admin.nav.system'=>'Sistema','admin.nav.file_manager'=>'Gestor de archivos','admin.nav.update'=>'Actualización','admin.nav.maintenance'=>'Modo mantenimiento','admin.nav.backups'=>'Copias de seguridad','admin.nav.reports'=>'Informes','admin.nav.user_reports'=>'Informes de usuarios','admin.nav.service_reports'=>'Informes de servicios','admin.nav.product_reports'=>'Informes de productos','admin.nav.logs'=>'Registros','admin.nav.access_logs'=>'Registros de acceso','admin.nav.activity_logs'=>'Registros de actividad','admin.nav.error_logs'=>'Registros de errores',
                'admin.menu.profile'=>'Mi perfil','admin.menu.password'=>'Cambiar contraseña','admin.menu.general_settings'=>'Ajustes generales','admin.menu.security'=>'Seguridad','admin.menu.manage_languages'=>'Gestionar idiomas','admin.account.kicker'=>'CUENTA Y SEGURIDAD','admin.account.title'=>'Cuenta de administrador','admin.account.subtitle'=>'Gestiona tu identidad, contraseña y estado de seguridad.','admin.account.identity'=>'Identidad del administrador','admin.account.updated'=>'Cuenta actualizada.','admin.password.title'=>'Cambiar contraseña','admin.password.help'=>'Usa al menos 12 caracteres. El cambio renueva tu sesión segura.','admin.password.current'=>'Contraseña actual','admin.password.new'=>'Nueva contraseña','admin.password.confirm'=>'Confirmar contraseña','admin.password.update'=>'Actualizar contraseña','admin.password.updated'=>'Contraseña actualizada de forma segura.','admin.security.title'=>'Estado de seguridad','admin.security.role'=>'Rol de administrador','admin.security.email'=>'Verificación de correo','admin.security.two_factor'=>'Autenticación de dos factores','admin.security.last_update'=>'Cuenta actualizada','admin.security.access_logs'=>'Revisar registros de acceso','common.full_name'=>'Nombre completo','common.username'=>'Usuario','common.email'=>'Correo electrónico','common.save_changes'=>'Guardar cambios','common.active'=>'Activo','common.verified'=>'Verificado','common.pending'=>'Pendiente','common.enabled'=>'Activado','common.disabled'=>'Desactivado',
            ],
            'de' => [
                'admin.nav.dashboard'=>'Dashboard','admin.nav.user_management'=>'Benutzerverwaltung','admin.nav.users'=>'Benutzer','admin.nav.groups'=>'Gruppen','admin.nav.roles'=>'Rollen','admin.nav.permissions'=>'Berechtigungen','admin.nav.order_management'=>'Auftragsverwaltung','admin.nav.imei_orders'=>'IMEI-Aufträge','admin.nav.server_orders'=>'Server-Aufträge','admin.nav.file_orders'=>'Datei-Aufträge','admin.nav.smm_orders'=>'SMM-Aufträge','admin.nav.product_orders'=>'Produktbestellungen','admin.nav.service_management'=>'Dienstverwaltung','admin.nav.service_groups'=>'Dienstgruppen','admin.nav.imei_services'=>'IMEI-Dienste','admin.nav.server_services'=>'Server-Dienste','admin.nav.file_services'=>'Dateidienste','admin.nav.smm_services'=>'SMM-Dienste','admin.nav.retail_store'=>'Shop','admin.nav.product_categories'=>'Produktkategorien','admin.nav.products'=>'Produkte','admin.nav.local_sources'=>'Lokale Quellen','admin.nav.sources'=>'Quellen','admin.nav.replies'=>'Antworten','admin.nav.downloads'=>'Downloads','admin.nav.download_categories'=>'Download-Kategorien','admin.nav.finances'=>'Finanzen','admin.nav.invoices'=>'Rechnungen','admin.nav.payment_reviews'=>'Zahlungsprüfung','admin.nav.statements'=>'Kontoauszüge','admin.nav.transactions'=>'Transaktionen','admin.nav.api_management'=>'API-Verwaltung','admin.nav.settings'=>'Einstellungen','admin.nav.general_settings'=>'Allgemeine Einstellungen','admin.nav.home_banners'=>'Startseiten-Banner','admin.nav.resellers'=>'Aufladehändler','admin.nav.mail_settings'=>'E-Mail-Einstellungen','admin.nav.payment_settings'=>'Zahlungseinstellungen','admin.nav.languages'=>'Sprachen','admin.nav.currencies'=>'Währungen','admin.nav.page_management'=>'Seitenverwaltung','admin.nav.system'=>'System','admin.nav.file_manager'=>'Dateimanager','admin.nav.update'=>'Aktualisierung','admin.nav.maintenance'=>'Wartungsmodus','admin.nav.backups'=>'Sicherungen','admin.nav.reports'=>'Berichte','admin.nav.user_reports'=>'Benutzerberichte','admin.nav.service_reports'=>'Dienstberichte','admin.nav.product_reports'=>'Produktberichte','admin.nav.logs'=>'Protokolle','admin.nav.access_logs'=>'Zugriffsprotokolle','admin.nav.activity_logs'=>'Aktivitätsprotokolle','admin.nav.error_logs'=>'Fehlerprotokolle',
                'admin.menu.profile'=>'Mein Profil','admin.menu.password'=>'Passwort ändern','admin.menu.general_settings'=>'Allgemeine Einstellungen','admin.menu.security'=>'Sicherheit','admin.menu.manage_languages'=>'Sprachen verwalten','admin.account.kicker'=>'KONTO & SICHERHEIT','admin.account.title'=>'Administratorkonto','admin.account.subtitle'=>'Verwalten Sie Identität, Passwort und Sicherheitsstatus.','admin.account.identity'=>'Administratoridentität','admin.account.updated'=>'Konto aktualisiert.','admin.password.title'=>'Passwort ändern','admin.password.help'=>'Verwenden Sie mindestens 12 Zeichen. Die sichere Sitzung wird erneuert.','admin.password.current'=>'Aktuelles Passwort','admin.password.new'=>'Neues Passwort','admin.password.confirm'=>'Neues Passwort bestätigen','admin.password.update'=>'Passwort aktualisieren','admin.password.updated'=>'Passwort sicher aktualisiert.','admin.security.title'=>'Sicherheitsstatus','admin.security.role'=>'Administratorrolle','admin.security.email'=>'E-Mail-Verifizierung','admin.security.two_factor'=>'Zwei-Faktor-Authentifizierung','admin.security.last_update'=>'Konto aktualisiert','admin.security.access_logs'=>'Zugriffsprotokolle prüfen','common.full_name'=>'Vollständiger Name','common.username'=>'Benutzername','common.email'=>'E-Mail-Adresse','common.save_changes'=>'Änderungen speichern','common.active'=>'Aktiv','common.verified'=>'Verifiziert','common.pending'=>'Ausstehend','common.enabled'=>'Aktiviert','common.disabled'=>'Deaktiviert',
            ],
            'tr' => [
                'admin.nav.dashboard'=>'Kontrol paneli','admin.nav.user_management'=>'Kullanıcı yönetimi','admin.nav.users'=>'Kullanıcılar','admin.nav.groups'=>'Gruplar','admin.nav.roles'=>'Roller','admin.nav.permissions'=>'İzinler','admin.nav.order_management'=>'Sipariş yönetimi','admin.nav.imei_orders'=>'IMEI siparişleri','admin.nav.server_orders'=>'Sunucu siparişleri','admin.nav.file_orders'=>'Dosya siparişleri','admin.nav.smm_orders'=>'SMM siparişleri','admin.nav.product_orders'=>'Ürün siparişleri','admin.nav.service_management'=>'Hizmet yönetimi','admin.nav.service_groups'=>'Hizmet grupları','admin.nav.imei_services'=>'IMEI hizmetleri','admin.nav.server_services'=>'Sunucu hizmetleri','admin.nav.file_services'=>'Dosya hizmetleri','admin.nav.smm_services'=>'SMM hizmetleri','admin.nav.retail_store'=>'Mağaza','admin.nav.product_categories'=>'Ürün kategorileri','admin.nav.products'=>'Ürünler','admin.nav.local_sources'=>'Yerel kaynaklar','admin.nav.sources'=>'Kaynaklar','admin.nav.replies'=>'Yanıtlar','admin.nav.downloads'=>'İndirmeler','admin.nav.download_categories'=>'İndirme kategorileri','admin.nav.finances'=>'Finans','admin.nav.invoices'=>'Faturalar','admin.nav.payment_reviews'=>'Ödeme incelemeleri','admin.nav.statements'=>'Hesap özetleri','admin.nav.transactions'=>'İşlemler','admin.nav.api_management'=>'API yönetimi','admin.nav.settings'=>'Ayarlar','admin.nav.general_settings'=>'Genel ayarlar','admin.nav.home_banners'=>'Ana sayfa bannerları','admin.nav.resellers'=>'Bakiye bayileri','admin.nav.mail_settings'=>'E-posta ayarları','admin.nav.payment_settings'=>'Ödeme ayarları','admin.nav.languages'=>'Diller','admin.nav.currencies'=>'Para birimleri','admin.nav.page_management'=>'Sayfa yönetimi','admin.nav.system'=>'Sistem','admin.nav.file_manager'=>'Dosya yöneticisi','admin.nav.update'=>'Güncelleme','admin.nav.maintenance'=>'Bakım modu','admin.nav.backups'=>'Yedekler','admin.nav.reports'=>'Raporlar','admin.nav.user_reports'=>'Kullanıcı raporları','admin.nav.service_reports'=>'Hizmet raporları','admin.nav.product_reports'=>'Ürün raporları','admin.nav.logs'=>'Günlükler','admin.nav.access_logs'=>'Erişim günlükleri','admin.nav.activity_logs'=>'Etkinlik günlükleri','admin.nav.error_logs'=>'Hata günlükleri',
                'admin.menu.profile'=>'Profilim','admin.menu.password'=>'Şifre değiştir','admin.menu.general_settings'=>'Genel ayarlar','admin.menu.security'=>'Güvenlik','admin.menu.manage_languages'=>'Dilleri yönet','admin.account.kicker'=>'HESAP VE GÜVENLİK','admin.account.title'=>'Yönetici hesabı','admin.account.subtitle'=>'Yönetici kimliğinizi, şifrenizi ve güvenlik durumunuzu yönetin.','admin.account.identity'=>'Yönetici kimliği','admin.account.updated'=>'Hesap güncellendi.','admin.password.title'=>'Şifre değiştir','admin.password.help'=>'En az 12 karakter kullanın. Güvenli oturumunuz yenilenir.','admin.password.current'=>'Mevcut şifre','admin.password.new'=>'Yeni şifre','admin.password.confirm'=>'Yeni şifreyi doğrula','admin.password.update'=>'Şifreyi güncelle','admin.password.updated'=>'Şifre güvenli şekilde güncellendi.','admin.security.title'=>'Güvenlik durumu','admin.security.role'=>'Yönetici rolü','admin.security.email'=>'E-posta doğrulama','admin.security.two_factor'=>'İki faktörlü doğrulama','admin.security.last_update'=>'Hesap güncellendi','admin.security.access_logs'=>'Erişim günlüklerini incele','common.full_name'=>'Ad soyad','common.username'=>'Kullanıcı adı','common.email'=>'E-posta adresi','common.save_changes'=>'Değişiklikleri kaydet','common.active'=>'Aktif','common.verified'=>'Doğrulandı','common.pending'=>'Beklemede','common.enabled'=>'Etkin','common.disabled'=>'Devre dışı',
            ],
        ];

        $now = now();
        foreach ($sets as $code => $translations) {
            $languageId = DB::table('languages')->where('code', $code)->value('id');
            if (! $languageId) continue;
            foreach ($translations as $key => $value) {
                DB::table('language_translations')->updateOrInsert(
                    ['language_id' => $languageId, 'translation_key' => $key],
                    ['value' => $value, 'updated_at' => $now, 'created_at' => $now]
                );
            }
        }
    }

    public function down(): void {}
};
