<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        if (! Schema::hasTable('languages') || ! Schema::hasTable('language_translations')) return;
        $sets = [
            'ar'=>['admin.dashboard.title'=>'لوحة العمليات المباشرة','admin.dashboard.kicker'=>'معلومات الأعمال في الوقت الفعلي','admin.dashboard.welcome'=>'مرحبًا بعودتك، :name','admin.dashboard.subtitle'=>'رؤى مباشرة من منصتك','admin.dashboard.auto_refresh'=>'تحديث تلقائي','admin.dashboard.today_orders'=>'طلبات اليوم','admin.dashboard.today_registrations'=>'تسجيلات اليوم','admin.dashboard.today_payments'=>'مدفوعات اليوم','admin.dashboard.today_profit'=>'أرباح اليوم','admin.dashboard.online_users'=>'المستخدمون المتصلون','admin.dashboard.live_total'=>'الإجمالي المباشر','admin.dashboard.monthly_profit'=>'الربح الشهري','admin.dashboard.vs_last_month'=>'مقارنة بالشهر الماضي','admin.dashboard.acceptance_rate'=>'نسبة قبول الطلبات','admin.dashboard.rejection_rate'=>'نسبة رفض الطلبات','admin.dashboard.total'=>'الإجمالي','admin.dashboard.pending_approval'=>'بانتظار الموافقة','admin.dashboard.no_pending'=>'لا توجد طلبات بانتظار الموافقة.','admin.dashboard.payment_alerts'=>'تنبيهات مراجعة المدفوعات','admin.dashboard.no_payment_alerts'=>'لا توجد مدفوعات تحتاج إلى مراجعة.','admin.dashboard.recent_orders'=>'أحدث الطلبات','admin.dashboard.this_month'=>'هذا الشهر','admin.dashboard.live_activity'=>'النشاط المباشر','admin.dashboard.no_activity'=>'لا يوجد نشاط حديث.','common.view_all'=>'عرض الكل'],
            'fr'=>['admin.dashboard.title'=>'Tableau des opérations en direct','admin.dashboard.kicker'=>'INFORMATIONS COMMERCIALES EN TEMPS RÉEL','admin.dashboard.welcome'=>'Bon retour, :name','admin.dashboard.subtitle'=>'Informations en direct de votre plateforme','admin.dashboard.auto_refresh'=>'Actualisation automatique','admin.dashboard.today_orders'=>'Commandes du jour','admin.dashboard.today_registrations'=>'Inscriptions du jour','admin.dashboard.today_payments'=>'Paiements du jour','admin.dashboard.today_profit'=>'Bénéfice du jour','admin.dashboard.online_users'=>'Utilisateurs en ligne','admin.dashboard.live_total'=>'Total en direct','admin.dashboard.monthly_profit'=>'Bénéfice mensuel','admin.dashboard.vs_last_month'=>'par rapport au mois dernier','admin.dashboard.acceptance_rate'=>'Taux d’acceptation','admin.dashboard.rejection_rate'=>'Taux de rejet','admin.dashboard.total'=>'Total','admin.dashboard.pending_approval'=>'En attente d’approbation','admin.dashboard.no_pending'=>'Aucune commande en attente.','admin.dashboard.payment_alerts'=>'Alertes de vérification des paiements','admin.dashboard.no_payment_alerts'=>'Aucun paiement à vérifier.','admin.dashboard.recent_orders'=>'Commandes récentes','admin.dashboard.this_month'=>'ce mois-ci','admin.dashboard.live_activity'=>'Activité en direct','admin.dashboard.no_activity'=>'Aucune activité récente.','common.view_all'=>'Tout afficher'],
            'es'=>['admin.dashboard.title'=>'Panel de operaciones en vivo','admin.dashboard.kicker'=>'INTELIGENCIA EMPRESARIAL EN TIEMPO REAL','admin.dashboard.welcome'=>'Bienvenido de nuevo, :name','admin.dashboard.subtitle'=>'Información en vivo de tu plataforma','admin.dashboard.auto_refresh'=>'Actualización automática','admin.dashboard.today_orders'=>'Pedidos de hoy','admin.dashboard.today_registrations'=>'Registros de hoy','admin.dashboard.today_payments'=>'Pagos de hoy','admin.dashboard.today_profit'=>'Beneficio de hoy','admin.dashboard.online_users'=>'Usuarios en línea','admin.dashboard.live_total'=>'Total en vivo','admin.dashboard.monthly_profit'=>'Beneficio mensual','admin.dashboard.vs_last_month'=>'frente al mes pasado','admin.dashboard.acceptance_rate'=>'Tasa de aceptación','admin.dashboard.rejection_rate'=>'Tasa de rechazo','admin.dashboard.total'=>'Total','admin.dashboard.pending_approval'=>'Pendiente de aprobación','admin.dashboard.no_pending'=>'No hay pedidos pendientes.','admin.dashboard.payment_alerts'=>'Alertas de revisión de pagos','admin.dashboard.no_payment_alerts'=>'No hay pagos para revisar.','admin.dashboard.recent_orders'=>'Pedidos recientes','admin.dashboard.this_month'=>'este mes','admin.dashboard.live_activity'=>'Actividad en vivo','admin.dashboard.no_activity'=>'No hay actividad reciente.','common.view_all'=>'Ver todo'],
            'de'=>['admin.dashboard.title'=>'Live-Betriebsübersicht','admin.dashboard.kicker'=>'GESCHÄFTSDATEN IN ECHTZEIT','admin.dashboard.welcome'=>'Willkommen zurück, :name','admin.dashboard.subtitle'=>'Live-Einblicke aus Ihrer Plattform','admin.dashboard.auto_refresh'=>'Automatische Aktualisierung','admin.dashboard.today_orders'=>'Heutige Aufträge','admin.dashboard.today_registrations'=>'Heutige Registrierungen','admin.dashboard.today_payments'=>'Heutige Zahlungen','admin.dashboard.today_profit'=>'Heutiger Gewinn','admin.dashboard.online_users'=>'Online-Benutzer','admin.dashboard.live_total'=>'Live-Gesamtwert','admin.dashboard.monthly_profit'=>'Monatlicher Gewinn','admin.dashboard.vs_last_month'=>'gegenüber letztem Monat','admin.dashboard.acceptance_rate'=>'Annahmequote','admin.dashboard.rejection_rate'=>'Ablehnungsquote','admin.dashboard.total'=>'Gesamt','admin.dashboard.pending_approval'=>'Wartet auf Genehmigung','admin.dashboard.no_pending'=>'Keine Aufträge warten auf Genehmigung.','admin.dashboard.payment_alerts'=>'Zahlungsprüfungen','admin.dashboard.no_payment_alerts'=>'Keine Zahlungen zu prüfen.','admin.dashboard.recent_orders'=>'Letzte Aufträge','admin.dashboard.this_month'=>'diesen Monat','admin.dashboard.live_activity'=>'Live-Aktivität','admin.dashboard.no_activity'=>'Keine aktuelle Aktivität.','common.view_all'=>'Alle anzeigen'],
            'tr'=>['admin.dashboard.title'=>'Canlı operasyon paneli','admin.dashboard.kicker'=>'GERÇEK ZAMANLI İŞ ZEKÂSI','admin.dashboard.welcome'=>'Tekrar hoş geldiniz, :name','admin.dashboard.subtitle'=>'Platformunuzdan canlı bilgiler','admin.dashboard.auto_refresh'=>'Otomatik yenileniyor','admin.dashboard.today_orders'=>'Bugünkü siparişler','admin.dashboard.today_registrations'=>'Bugünkü kayıtlar','admin.dashboard.today_payments'=>'Bugünkü ödemeler','admin.dashboard.today_profit'=>'Bugünkü kâr','admin.dashboard.online_users'=>'Çevrimiçi kullanıcılar','admin.dashboard.live_total'=>'Canlı toplam','admin.dashboard.monthly_profit'=>'Aylık kâr','admin.dashboard.vs_last_month'=>'geçen aya göre','admin.dashboard.acceptance_rate'=>'Sipariş kabul oranı','admin.dashboard.rejection_rate'=>'Sipariş ret oranı','admin.dashboard.total'=>'Toplam','admin.dashboard.pending_approval'=>'Onay bekleyenler','admin.dashboard.no_pending'=>'Onay bekleyen sipariş yok.','admin.dashboard.payment_alerts'=>'Ödeme inceleme uyarıları','admin.dashboard.no_payment_alerts'=>'İncelenecek ödeme yok.','admin.dashboard.recent_orders'=>'Son siparişler','admin.dashboard.this_month'=>'bu ay','admin.dashboard.live_activity'=>'Canlı etkinlik','admin.dashboard.no_activity'=>'Son etkinlik yok.','common.view_all'=>'Tümünü gör'],
        ];
        $now=now();
        foreach($sets as $code=>$translations){
            $languageId=DB::table('languages')->where('code',$code)->value('id');
            if(!$languageId)continue;
            foreach($translations as $key=>$value)DB::table('language_translations')->updateOrInsert(
                ['language_id'=>$languageId,'translation_key'=>$key],
                ['value'=>$value,'updated_at'=>$now,'created_at'=>$now]
            );
        }
    }
    public function down(): void {}
};
