@extends('layouts.admin')
@section('title', 'Currencies')
@section('content')
<div class="card"><div class="card-header bg-primary text-white d-flex justify-content-between align-items-center"><span><i class="fas fa-coins me-1"></i> Currencies</span><button class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#createCurrency">Add currency</button></div><div class="card-body">
  @if(session('ok'))<div class="alert alert-success">{{ session('ok') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
  <div class="alert alert-info small">Exchange rate means the number of currency units equal to one unit of the default currency. The default currency always has rate 1.</div>
  <div class="table-responsive"><table class="table table-striped align-middle"><thead><tr><th>Currency</th><th>Symbol</th><th>Rate</th><th>Example</th><th>Status</th><th>Updated</th><th class="text-end">Actions</th></tr></thead><tbody>
    @foreach($currencies as $currency)<tr><td><strong>{{ $currency->code }}</strong> — {{ $currency->name }} @if($currency->is_default)<span class="badge bg-primary">Default</span>@endif</td><td>{{ $currency->symbol }}</td><td>{{ $currency->exchange_rate }}</td><td>{{ app(\App\Services\Settings\CurrencyConverter::class)->format('1234.5', $currency) }}</td><td><span class="badge {{ $currency->active ? 'bg-success' : 'bg-secondary' }}">{{ $currency->active ? 'Active' : 'Inactive' }}</span></td><td>{{ $currency->rate_updated_at?->format('Y-m-d H:i') }}</td><td class="text-end text-nowrap"><button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#editCurrency{{ $currency->id }}">Edit</button> @unless($currency->is_default)<form class="d-inline" method="POST" action="{{ route('admin.settings.currencies.destroy', $currency) }}" onsubmit="return confirm('Delete this currency?')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm">Delete</button></form>@endunless</td></tr>@endforeach
  </tbody></table></div>
</div></div>
<div class="modal fade" id="createCurrency" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('admin.settings.currencies.store') }}">@csrf<div class="modal-header"><h5 class="modal-title">Add currency</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('admin.settings.currencies.partials.form', ['currency' => null])</div><div class="modal-footer"><button class="btn btn-primary">Create</button></div></form></div></div>
@foreach($currencies as $currency)<div class="modal fade" id="editCurrency{{ $currency->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('admin.settings.currencies.update', $currency) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Edit {{ $currency->code }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('admin.settings.currencies.partials.form', ['currency' => $currency])</div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>@endforeach
@endsection
