@extends('layouts.customer')
@section('title','Overview')
@section('content')
<div class="d-flex justify-content-between align-items-start mb-4"><div><h1 class="section-title h2 mb-1">Welcome back, {{ str(auth()->user()->name)->before(' ') }} 👋</h1><div class="text-muted">Here’s what’s happening with your account today.</div></div><div class="small text-muted">{{ now()->format('D, M j Y') }}</div></div>
<div class="balance-card p-4 mb-4"><div class="row align-items-center position-relative" style="z-index:1"><div class="col-md"><div class="text-muted fw-semibold">Available balance</div><div class="display-5 fw-bold">${{ number_format((float)auth()->user()->balance,2) }}</div></div><div class="col-md-auto mt-3 mt-md-0"><a class="btn btn-gsm btn-lg" href="{{ route('customer.payments.create') }}"><i class="fas fa-circle-plus me-2"></i>Add funds</a></div></div></div>
<div class="gsm-card p-3 p-lg-4 mb-4"><div class="d-flex justify-content-between mb-3"><div><h3 class="h5 fw-bold mb-1">Quick order</h3><div class="small text-muted">Choose a service type to get started.</div></div><a href="{{ route('site.services') }}">View all</a></div><div class="row g-3">@foreach([['IMEI','Unlock, check and clean','mobile-screen'],['Server','Credits and activations','server'],['File','Firmware and certificates','file-lines'],['SMM','Social media services','users']] as $item)<div class="col-6 col-xl-3"><a href="{{ route('site.services',['type'=>strtolower($item[0])]) }}" class="text-decoration-none text-dark"><div class="border rounded-4 p-3 h-100 d-flex gap-3"><div class="service-icon"><i class="fas fa-{{ $item[2] }}"></i></div><div><div class="fw-bold">{{ $item[0] }}</div><div class="small text-muted">{{ $item[1] }}</div></div></div></a></div>@endforeach</div></div>
<div class="row g-3 mb-4">@foreach([['Orders in progress',$stats['progress'],'clock','primary'],['Completed orders',$stats['completed'],'circle-check','success'],['Waiting for action',$stats['waiting'],'hourglass-half','warning'],['Total orders',$stats['total'],'chart-line','info']] as $stat)<div class="col-6 col-xl-3"><div class="stat-card"><div class="d-flex align-items-center gap-3"><div class="service-icon text-{{ $stat[3] }}"><i class="fas fa-{{ $stat[2] }}"></i></div><div><div class="small text-muted">{{ $stat[0] }}</div><div class="h3 fw-bold mb-0">{{ $stat[1] }}</div></div></div></div></div>@endforeach</div>
<div class="gsm-card p-3 p-lg-4"><div class="d-flex justify-content-between mb-3"><h3 class="h5 fw-bold">Recent orders</h3><a href="{{ route('customer.orders') }}">View all orders</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Order</th><th>Service</th><th>Details</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead><tbody>@forelse($recentOrders as $order)<tr><td>#{{ $order['type'] }}-{{ $order['id'] }}</td><td class="fw-semibold">{{ $order['service'] }}</td><td>{{ $order['device'] }}</td><td><span class="status-pill status-{{ str($order['status'])->lower()->replace(' ','-') }}">{{ $order['status'] }}</span></td><td>${{ number_format((float)$order['amount'],2) }}</td><td>{{ $order['created_at']?->format('M j, Y') }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">No orders yet. Start with a service above.</td></tr>@endforelse</tbody></table></div></div>
@endsection
