@extends(auth()->check() ? 'layouts.customer' : 'layouts.site')
@section('title','Downloads')
@section('content')
<section class="{{ auth()->check()?'':'container py-5 mt-5' }}"><div class="page-heading"><div><span class="eyebrow">DOWNLOAD CENTER</span><h1>Files, tools and resources</h1><p>Free, private and premium resources published by our team.</p></div></div><div class="row g-3">
@forelse($downloads as $download)<div class="col-md-6"><article class="gsm-card p-4 h-100 d-flex gap-3"><div class="service-icon flex-shrink-0"><i class="fas fa-file-arrow-down"></i></div><div class="flex-grow-1 d-flex flex-column"><div class="d-flex justify-content-between gap-2"><h2 class="h5 fw-bold mb-1">{{ $download->name }}</h2><span class="badge {{ $download->visibility==='paid'?'text-bg-warning':($download->visibility==='private'?'text-bg-primary':'text-bg-success') }}">{{ $download->visibility==='paid'?number_format((float)$download->price,2).' credits':ucfirst($download->visibility) }}</span></div><div class="text-muted small mb-2">{!! Illuminate\Support\Str::limit(strip_tags($download->description),180) !!}</div><div class="small text-muted mb-3">{{ $download->version ? 'Version '.$download->version : 'Latest version' }} @if($download->size) · {{ number_format($download->size/1048576,1) }} MB @endif</div><div class="mt-auto">
@guest<a class="btn btn-gsm w-100" href="{{ route('login') }}">Log in to download</a>
@else
 @if($download->visibility==='paid' && !($download->purchased??false))<button class="btn btn-gsm w-100 js-buy-download" data-url="{{ route('customer.downloads.purchase',$download) }}" data-funds="{{ route('customer.payments.create') }}">Buy & download</button>
 @else<a class="btn btn-gsm w-100" href="{{ route('customer.downloads.download',$download) }}">Download <i class="fas fa-download ms-1"></i></a>@endif
@endguest
</div></div></article></div>@empty<div class="col-12"><div class="empty-state"><i class="fas fa-cloud-arrow-down"></i><h2>No downloads available</h2></div></div>@endforelse</div><div class="mt-4">{{ $downloads->links() }}</div></section>
@auth @push('scripts')<script>document.querySelectorAll('.js-buy-download').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('Purchase this download from your balance?'))return;button.disabled=true;const response=await fetch(button.dataset.url,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}}),data=await response.json().catch(()=>({}));if(response.ok){location.href=data.download_url;return}if(response.status===422&&data.errors?.balance){if(confirm(data.errors.balance[0]+' Open Add Funds?'))location.href=button.dataset.funds}else alert(data.message||'The purchase could not be completed.');button.disabled=false}))</script>@endpush @endauth
@endsection
