@extends(auth()->check() ? 'layouts.customer' : 'layouts.site')
@section('title','Downloads')
@section('content')
<section class="{{ auth()->check()?'':'container py-5 mt-5' }}"><div class="page-heading"><div><span class="eyebrow">DOWNLOAD CENTER</span><h1>Files, tools and resources</h1><p>Free, private and premium resources published by our team.</p></div></div><div class="row g-3">
@forelse($downloads as $download)<div class="col-md-6"><article class="gsm-card p-4 h-100 d-flex gap-3"><div class="service-icon flex-shrink-0"><i class="fas fa-file-arrow-down"></i></div><div class="flex-grow-1 d-flex flex-column"><div class="d-flex justify-content-between gap-2"><h2 class="h5 fw-bold mb-1">{{ $download->name }}</h2><span class="badge {{ $download->visibility==='paid'?'text-bg-warning':($download->visibility==='private'?'text-bg-primary':'text-bg-success') }}">{{ $download->visibility==='paid'?number_format((float)$download->price,2).' credits':ucfirst($download->visibility) }}</span></div><div class="text-muted small mb-2">{{ Illuminate\Support\Str::limit(strip_tags($download->description),180) }}</div><div class="small text-muted mb-3">{{ $download->version ? 'Version '.$download->version : 'Latest version' }} @if($download->size) · {{ number_format($download->size/1048576,1) }} MB @endif</div><div class="mt-auto">
@guest<a class="btn btn-gsm w-100" href="{{ route('login') }}">Log in to download</a>
@else
 @if($download->visibility==='paid' && !($download->purchased??false))<button class="btn btn-gsm w-100 js-buy-download" data-url="{{ route('customer.downloads.purchase',$download) }}" data-funds="{{ route('customer.payments.create') }}" data-name="{{ $download->name }}" data-price="{{ number_format((float)$download->price,2,'.','') }}">Buy & download</button>
 @else<a class="btn btn-gsm w-100" href="{{ route('customer.downloads.download',$download) }}">Download <i class="fas fa-download ms-1"></i></a>@endif
@endguest
</div></div></article></div>@empty<div class="col-12"><div class="empty-state"><i class="fas fa-cloud-arrow-down"></i><h2>No downloads available</h2></div></div>@endforelse</div><div class="mt-4">{{ $downloads->links() }}</div></section>
@auth
<div class="modal fade" id="downloadPurchaseModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content purchase-modal"><div class="modal-body p-4 p-md-5"><button type="button" class="btn-close purchase-close" data-bs-dismiss="modal" aria-label="Close"></button><div id="purchaseConfirm"><div class="purchase-icon"><i class="fas fa-shield-halved"></i></div><span class="eyebrow">SECURE PURCHASE</span><h2 class="h3 fw-bold mt-2">Confirm your download</h2><p class="text-muted">The price will be deducted once from your available balance.</p><div class="purchase-summary"><span>File<strong id="purchaseName"></strong></span><span>Amount<strong><b id="purchasePrice"></b> credits</strong></span></div><div id="purchaseError" class="alert alert-danger d-none"></div><div class="d-grid gap-2 mt-4"><button class="btn btn-gsm" id="confirmPurchase"><span>Pay & unlock download</span><i class="fas fa-arrow-right ms-2"></i></button><button class="btn btn-light" data-bs-dismiss="modal">Cancel</button></div></div><div id="purchaseSuccess" class="d-none text-center"><div class="purchase-icon success"><i class="fas fa-check"></i></div><span class="eyebrow">PAYMENT COMPLETE</span><h2 class="h3 fw-bold mt-2">Your file is ready</h2><p class="text-muted" id="purchaseResult"></p><div class="purchase-balance"><span>New balance</span><strong id="purchaseBalance"></strong></div><a class="btn btn-gsm w-100 mt-4" id="purchaseDownload"><i class="fas fa-download me-2"></i>Download now</a><a class="btn btn-link w-100 mt-2" href="{{ route('customer.payments.index') }}">View account statement</a></div></div></div></div></div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const modalElement=document.getElementById('downloadPurchaseModal'),modal=bootstrap.Modal.getOrCreateInstance(modalElement),confirmBox=document.getElementById('purchaseConfirm'),successBox=document.getElementById('purchaseSuccess'),confirmButton=document.getElementById('confirmPurchase'),errorBox=document.getElementById('purchaseError');let selected=null;document.querySelectorAll('.js-buy-download').forEach(button=>button.addEventListener('click',()=>{selected=button;confirmBox.classList.remove('d-none');successBox.classList.add('d-none');errorBox.classList.add('d-none');document.getElementById('purchaseName').textContent=button.dataset.name;document.getElementById('purchasePrice').textContent=button.dataset.price;modal.show()}));confirmButton.addEventListener('click',async()=>{if(!selected)return;confirmButton.disabled=true;errorBox.classList.add('d-none');try{const response=await fetch(selected.dataset.url,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}}),data=await response.json().catch(()=>({}));if(!response.ok){if(response.status===422&&data.errors?.balance){errorBox.innerHTML=`${data.errors.balance[0]} <a class="alert-link" href="${selected.dataset.funds}">Add funds</a>`}else errorBox.textContent=data.message||'The purchase could not be completed.';errorBox.classList.remove('d-none');return}document.querySelectorAll('.top-balance strong').forEach(el=>el.textContent=`$${Number(data.balance).toFixed(2)}`);document.getElementById('purchaseBalance').textContent=`$${Number(data.balance).toFixed(2)}`;document.getElementById('purchaseResult').textContent=data.charged?`${Number(data.amount).toFixed(2)} credits were deducted successfully.`:'This download was already purchased. No additional charge was made.';document.getElementById('purchaseDownload').href=data.download_url;selected.outerHTML=`<a class="btn btn-gsm w-100" href="${data.download_url}">Download <i class="fas fa-download ms-1"></i></a>`;confirmBox.classList.add('d-none');successBox.classList.remove('d-none')}catch(e){errorBox.textContent='Connection failed. Your balance was not charged twice; please check your statement before retrying.';errorBox.classList.remove('d-none')}finally{confirmButton.disabled=false}})});</script>@endpush
@endauth
@endsection
