@extends('layouts.customer')
@section('title','Account settings')
@section('content')
@php($twoFactorRequired=(bool)app(\App\Services\Settings\AppSettings::class)->get('general.two_factor_enabled',false))
<div class="row g-4"><div class="col-xl-8">
<div class="panel-card"><span class="eyebrow">ACCOUNT</span><h1 class="h3 fw-bold">Profile settings</h1><p class="text-muted">Keep your contact and account information current.</p>
<form method="POST" action="{{ route('customer.profile.update') }}">@csrf @method('PUT')<div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control form-control-lg" name="name" value="{{ old('name',$user->name) }}" required></div><div class="col-md-6"><label class="form-label">Username</label><input class="form-control form-control-lg" name="username" value="{{ old('username',$user->username) }}" required></div><div class="col-12"><label class="form-label">Email address</label><input type="email" class="form-control form-control-lg" name="email" value="{{ old('email',$user->email) }}" required></div></div><button class="btn btn-primary btn-lg mt-4 px-4">Save changes</button></form></div>
<div class="panel-card mt-4"><h2 class="h5 fw-bold">Two-step verification</h2>
@if($twoFactorRequired)<div class="alert alert-info mb-0"><i class="fas fa-shield-halved me-2"></i>Email two-step verification is required for all users by the administrator.</div>
@else<p class="text-muted">Protect your account with a one-time email code after password or Google sign-in.</p><form method="POST" action="{{ route('customer.profile.two-factor') }}">@csrf @method('PUT')<input type="hidden" name="enabled" value="{{ $user->two_factor_enabled?0:1 }}">@if(!$user->google_id)<label class="form-label">Confirm current password</label><input type="password" name="password" class="form-control" required autocomplete="current-password">@endif<button class="btn {{ $user->two_factor_enabled?'btn-outline-danger':'btn-outline-primary' }} mt-3">{{ $user->two_factor_enabled?'Disable':'Enable' }} two-step verification</button></form>@endif
</div></div><div class="col-xl-4"><div class="balance-card"><div class="small text-white-50">Available balance</div><div class="display-6 fw-bold">${{ number_format($user->balance ?? 0,2) }}</div><a class="btn btn-light mt-3" href="{{ route('customer.payments.create') }}">Add funds</a></div></div></div>
@endsection
