@extends('layouts.customer')
@section('title','Account settings')
@section('content')
@php($twoFactorRequired=(bool)app(\App\Services\Settings\AppSettings::class)->get('general.two_factor_enabled',false))
@include('customer.partials.passkeys')
<div class="row g-4"><div class="col-xl-8">
<div class="panel-card"><span class="eyebrow">ACCOUNT</span><h1 class="h3 fw-bold">Profile settings</h1><p class="text-muted">Keep your contact and account information current.</p><form method="POST" action="{{ route('customer.profile.update') }}">@csrf @method('PUT')<div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control form-control-lg" name="name" value="{{ old('name',$user->name) }}" required></div><div class="col-md-6"><label class="form-label">Username</label><input class="form-control form-control-lg" name="username" value="{{ old('username',$user->username) }}" required></div><div class="col-12"><label class="form-label">Email address</label><input type="email" class="form-control form-control-lg" name="email" value="{{ old('email',$user->email) }}" required></div></div><button class="btn btn-primary btn-lg mt-4 px-4">Save changes</button></form></div>
<div class="panel-card mt-4"><div class="d-flex justify-content-between align-items-start"><div><h2 class="h5 fw-bold">Two-step verification</h2><p class="text-muted">Choose email codes or an authenticator app.</p></div>@if($twoFactorRequired)<span class="badge bg-primary">Required by administrator</span>@endif</div>
<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between align-items-center"><div><strong>Email verification</strong><div class="small text-muted">Receive a six-digit code by email.</div></div>
@if($twoFactorRequired)<span class="badge bg-success">Available fallback</span>@elseif($user->two_factor_method==='email')<form method="POST" action="{{ route('customer.profile.two-factor') }}">@csrf @method('PUT')<input type="hidden" name="enabled" value="{{ $user->two_factor_enabled?0:1 }}">@if(!$user->google_id)<input type="password" name="password" class="form-control form-control-sm mb-2" placeholder="Current password" required>@endif<button class="btn btn-sm {{ $user->two_factor_enabled?'btn-outline-danger':'btn-outline-primary' }}">{{ $user->two_factor_enabled?'Disable':'Enable' }}</button></form>@endif</div></div>
<div class="border rounded p-3"><div class="d-flex justify-content-between align-items-center gap-3"><div><strong>Authenticator app</strong><div class="small text-muted">Works with Google Authenticator, Microsoft Authenticator and Authy, including offline codes.</div></div>
@if($user->two_factor_method==='authenticator'&&$user->two_factor_confirmed_at)<form method="POST" action="{{ route('customer.profile.authenticator.remove') }}">@csrf @method('DELETE')@if(!$user->google_id)<input type="password" name="password" class="form-control form-control-sm mb-2" placeholder="Current password" required autocomplete="current-password">@endif<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" class="form-control form-control-sm mb-2" placeholder="Authenticator code" required autocomplete="one-time-code"><button class="btn btn-sm btn-outline-danger">Remove</button></form>@else<form method="POST" action="{{ route('customer.profile.authenticator.setup') }}">@csrf @if(!$user->google_id)<input type="password" name="password" class="form-control form-control-sm mb-2" placeholder="Current password" required autocomplete="current-password">@endif<button class="btn btn-sm btn-outline-primary">Set up app</button></form>@endif</div></div>
</div></div><div class="col-xl-4"><div class="balance-card"><div class="small text-white-50">Available balance</div><div class="display-6 fw-bold">${{ number_format($user->balance ?? 0,2) }}</div><a class="btn btn-light mt-3" href="{{ route('customer.payments.create') }}">Add funds</a></div></div></div>
@if($authenticatorSetup)<div class="modal fade" id="authenticatorSetup" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5">Set up authenticator app</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body text-center"><p>Scan this QR code with your authenticator app.</p><canvas id="authenticatorQr" class="mw-100"></canvas><div class="small text-muted mt-3">Manual key</div><code class="user-select-all">{{ $authenticatorSetup['secret'] }}</code><form method="POST" action="{{ route('customer.profile.authenticator.confirm') }}" class="mt-4">@csrf<label class="form-label">Enter the current six-digit code</label><input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" class="form-control form-control-lg text-center" required autocomplete="one-time-code"><button class="btn btn-primary w-100 mt-3">Confirm and enable</button></form></div></div></div></div>@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const modal=document.getElementById('authenticatorSetup');window.bootstrap.Modal.getOrCreateInstance(modal).show();window.QRCode.toCanvas(document.getElementById('authenticatorQr'),@json($authenticatorSetup['uri']),{width:240,margin:2})});</script>@endpush @endif
@endsection
