@extends('layouts.admin')
@section('title', $page ? 'Edit page' : 'Create page')
@section('content')
<div class="card"><div class="card-header bg-primary text-white">{{ $page ? 'Edit '.$page->slug : 'Create page' }}</div><div class="card-body">
@if($page?->system)<div class="alert alert-info"><i class="fa-solid fa-shield-halved me-2"></i>Core page: its route and placement are protected, but you can publish or hide it and edit its content and SEO.</div>@endif
@if(session('ok'))<div class="alert alert-success">{{ session('ok') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $page ? route('admin.pages.update',$page) : route('admin.pages.store') }}">@csrf @if($page) @method('PUT') @endif
<div class="row g-3">
<div class="col-md-4"><label class="form-label">Slug</label><input class="form-control" name="slug" value="{{ old('slug',$page?->slug) }}" @readonly($page?->system) required></div>
<div class="col-md-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="draft" @selected(old('status',$page?->status)==='draft')>Hidden</option><option value="published" @selected(old('status',$page?->status)==='published')>Visible</option></select></div>
<div class="col-md-2"><label class="form-label">Placement</label><select class="form-select" name="placement" @disabled($page?->system)>@foreach(['header','footer','home','standalone'] as $place)<option @selected(old('placement',$page?->placement)===$place)>{{ $place }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">Order</label><input class="form-control" type="number" name="ordering" value="{{ old('ordering',$page?->ordering??0) }}" @readonly($page?->system)></div>
<div class="col-md-2"><label class="form-label">Publish at</label><input class="form-control" type="datetime-local" name="published_at" value="{{ old('published_at',$page?->published_at?->format('Y-m-d\TH:i')) }}" @readonly($page?->system)></div>
<div class="col-md-4"><label class="form-label">Parent</label><select class="form-select" name="parent_id" @disabled($page?->system)><option value="">None</option>@foreach($parents as $parent)<option value="{{ $parent->id }}" @selected(old('parent_id',$page?->parent_id)===$parent->id)>{{ $parent->slug }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Featured image path</label><input class="form-control" name="featured_image" value="{{ old('featured_image',$page?->featured_image) }}"></div>
<div class="col-md-4"><label class="form-label">Open Graph image path</label><input class="form-control" name="og_image" value="{{ old('og_image',$page?->og_image) }}"></div>
<div class="col-md-3 form-check ms-2"><input type="hidden" name="authenticated_only" value="0"><input class="form-check-input" type="checkbox" name="authenticated_only" value="1" @checked(old('authenticated_only',$page?->authenticated_only)) @disabled($page?->system)> Members only</div>
<div class="col-md-3 form-check"><input type="hidden" name="open_new_window" value="0"><input class="form-check-input" type="checkbox" name="open_new_window" value="1" @checked(old('open_new_window',$page?->open_new_window))> Open in new window</div>
</div><hr>
<ul class="nav nav-tabs">@foreach($languages as $language)<li class="nav-item"><button type="button" class="nav-link @if($loop->first) active @endif" data-bs-toggle="tab" data-bs-target="#lang{{ $language->id }}">{{ $language->native_name }}</button></li>@endforeach</ul>
<div class="tab-content border border-top-0 p-3">@foreach($languages as $i=>$language) @php($translation=collect(old('translations'))->firstWhere('language_id',$language->id) ?? $page?->translations?->firstWhere('language_id',$language->id))
<div class="tab-pane fade @if($loop->first) show active @endif" id="lang{{ $language->id }}"><input type="hidden" name="translations[{{ $i }}][language_id]" value="{{ $language->id }}"><div class="mb-3"><label class="form-label">Title</label><input class="form-control" name="translations[{{ $i }}][title]" value="{{ data_get($translation,'title') }}" required></div><div class="mb-3"><label class="form-label">Content</label><textarea class="form-control" rows="12" name="translations[{{ $i }}][content]">{{ data_get($translation,'content') }}</textarea></div><div class="row"><div class="col-md-6"><label class="form-label">SEO title</label><input class="form-control" name="translations[{{ $i }}][seo_title]" value="{{ data_get($translation,'seo_title') }}"></div><div class="col-md-6"><label class="form-label">SEO description</label><textarea class="form-control" name="translations[{{ $i }}][seo_description]">{{ data_get($translation,'seo_description') }}</textarea></div></div></div>@endforeach</div>
<button class="btn btn-primary mt-3"><i class="fa-solid fa-floppy-disk me-2"></i>Save page</button></form></div></div>
@endsection
