@extends('layouts.site')
@section('title','Professional GSM Services · '.config('app.name'))
@section('content')
<section class="hero"><div class="container position-relative" style="z-index:1"><div class="row align-items-center g-5"><div class="col-lg-7"><div class="badge rounded-pill border border-info-subtle bg-primary bg-opacity-10 text-info px-3 py-2 mb-4"><i class="fas fa-circle-check me-2"></i>Trusted by mobile professionals worldwide</div><h1>Unlock smarter.<br><span class="text-gradient">Work faster.</span></h1><p class="lead text-white-50 my-4" style="max-width:700px">Professional IMEI, server, file and social media services in one fast, secure platform.</p><div class="d-flex flex-wrap gap-3"><a class="btn btn-gsm btn-lg" href="{{ route('site.services') }}">Explore services <i class="fas fa-arrow-right ms-2"></i></a><a class="btn btn-outline-light btn-lg rounded-3" href="{{ route('register') }}">Create account</a></div><div class="d-flex flex-wrap gap-4 mt-5 small text-white-50"><span><i class="fas fa-shield-halved text-info me-2"></i>Secure & reliable</span><span><i class="fas fa-bolt text-info me-2"></i>Fast processing</span><span><i class="fas fa-headset text-info me-2"></i>Expert support</span></div></div><div class="col-lg-5"><div class="glass-card p-4 p-xl-5 text-center"><div style="font-size:6rem" class="text-info"><i class="fas fa-mobile-screen-button"></i></div><h3 class="fw-bold mt-3">One platform.<br>Every GSM workflow.</h3><p class="text-white-50 mb-0">Order, track, pay and deliver from anywhere.</p></div></div></div></div></section>
<section class="service-float"><div class="container"><div class="gsm-card p-3 p-lg-4"><form action="{{ route('site.services') }}" class="input-group input-group-lg mb-4"><span class="input-group-text bg-white border-end-0"><i class="fas fa-search"></i></span><input name="q" class="form-control border-start-0" placeholder="Search for a service: iCloud, Samsung FRP, server credit…"><button class="btn btn-gsm px-4">Search</button></form><div class="row g-3">@foreach([['imei','IMEI Services','Network unlock, blacklist and carrier services','mobile-screen-button'],['server','Server Services','Credits, activations and remote tools','server'],['file','File Services','Firmware, certificates and files','file-lines'],['smm','SMM Services','Social growth and engagement','users']] as $item)<div class="col-md-6 col-xl-3"><a href="{{ route('site.services',['type'=>$item[0]]) }}" class="text-decoration-none text-dark"><div class="d-flex gap-3 p-3 h-100 border rounded-4"><div class="service-icon"><i class="fas fa-{{ $item[3] }}"></i></div><div><h5 class="fw-bold mb-1">{{ $item[1] }}</h5><div class="small text-muted">{{ $item[2] }}</div><div class="small text-primary fw-bold mt-2">{{ $counts[$item[0]] }} available</div></div></div></a></div>@endforeach</div></div></div></section>
<section class="py-5"><div class="container"><div class="text-center mb-5"><div class="text-primary fw-bold text-uppercase small">Built for professionals</div><h2 class="section-title display-6">Everything you need to deliver faster</h2></div><div class="row g-4">@foreach([['clock','Real-time tracking','Follow every order from submission to completion.'],['wallet','Secure payments','Pay with PayPal, Binance Pay, USDT or manual methods.'],['globe','Global catalog','Access multiple service categories from one account.']] as $feature)<div class="col-md-4"><div class="gsm-card p-4 h-100"><div class="service-icon mb-3"><i class="fas fa-{{ $feature[0] }}"></i></div><h4 class="fw-bold">{{ $feature[1] }}</h4><p class="text-muted mb-0">{{ $feature[2] }}</p></div></div>@endforeach</div></div></section>
@if($products->isNotEmpty())<section class="py-5 bg-white"><div class="container"><div class="d-flex justify-content-between align-items-end mb-4"><div><div class="text-primary fw-bold small">STORE</div><h2 class="section-title mb-0">Latest products</h2></div><a href="{{ route('site.store') }}">View all products</a></div><div class="row g-4">@foreach($products as $product)<div class="col-6 col-lg-3"><div class="gsm-card p-3 h-100">@if($product->main_image)<img src="{{ asset($product->main_image) }}" class="img-fluid rounded-3 mb-3" alt="">@endif<div class="small text-muted">{{ $product->category?->name }}</div><h5 class="fw-bold">{{ $product->name }}</h5><div class="text-primary fw-bold">{{ number_format($product->price,2) }} {{ $product->currency ?: 'USD' }}</div></div></div>@endforeach</div></div></section>@endif
@if($page?->translations->first()?->content)<section class="py-5"><div class="container gsm-card p-4">{!! $page->translations->first()->content !!}</div></section>@endif
@endsection
