@extends('layouts.admin')
@section('title','Download categories')
@section('content')
<div class="admin-page-head"><div><span class="admin-kicker">DOWNLOADS</span><h1>Download categories</h1><p>Organize downloadable files without exposing editable fields in the list.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createCategory"><i class="fas fa-plus me-1"></i> New category</button></div>
@if(session('ok'))<div class="alert alert-success">{{ session('ok') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card admin-panel"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Category</th><th>Description</th><th>Permission</th><th>Files</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($categories as $category)
<tr><td><strong>{{ $category->name }}</strong><div class="small text-muted">Order {{ $category->ordering }}</div></td><td>{{ Str::limit($category->description ?: 'No description',70) }}</td><td><code>{{ $category->required_permission ?: 'Public' }}</code></td><td><span class="badge text-bg-light">{{ $category->downloads_count }}</span></td><td><span class="status-dot {{ $category->active?'is-active':'is-inactive' }}">{{ $category->active?'Active':'Inactive' }}</span></td><td class="text-end text-nowrap">
<a class="btn btn-sm btn-outline-primary" href="{{ route('admin.downloads.index',['category_id'=>$category->id]) }}" title="View files"><i class="fas fa-eye"></i></a>
<button class="btn btn-sm btn-warning js-edit-category" type="button" data-action="{{ route('admin.downloads.categories.update',$category) }}" data-name="{{ $category->name }}" data-description="{{ $category->description }}" data-permission="{{ $category->required_permission }}" data-ordering="{{ $category->ordering }}" data-active="{{ $category->active?1:0 }}" title="Edit"><i class="fas fa-pen"></i></button>
<form class="d-inline" method="POST" action="{{ route('admin.downloads.categories.destroy',$category) }}" onsubmit="return confirm('Delete this category?')">@csrf @method('DELETE')<button class="btn btn-sm btn-danger" title="Delete"><i class="fas fa-trash"></i></button></form>
</td></tr>
@empty<tr><td colspan="6" class="text-center text-muted py-5">No download categories yet.</td></tr>@endforelse
</tbody></table></div><div class="card-footer bg-white">{{ $categories->links() }}</div></div>
<div class="modal fade" id="createCategory" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" action="{{ route('admin.downloads.categories.store') }}">@csrf<div class="modal-header"><h2 class="modal-title h5">New download category</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div>@include('admin.downloads.partials.category-fields',['prefix'=>'create'])<div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Create category</button></div></form></div></div>
<div class="modal fade" id="editCategory" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" method="POST" id="editCategoryForm">@csrf @method('PUT')<div class="modal-header"><h2 class="modal-title h5">Edit download category</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div>@include('admin.downloads.partials.category-fields',['prefix'=>'edit'])<div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-warning">Save changes</button></div></form></div></div>
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const modal=document.getElementById('editCategory'),form=document.getElementById('editCategoryForm');document.querySelectorAll('.js-edit-category').forEach(button=>button.addEventListener('click',()=>{form.action=button.dataset.action;form.querySelector('[name=name]').value=button.dataset.name||'';form.querySelector('[name=description]').value=button.dataset.description||'';form.querySelector('[name=required_permission]').value=button.dataset.permission||'';form.querySelector('[name=ordering]').value=button.dataset.ordering||0;form.querySelector('[name=active]').checked=button.dataset.active==='1';bootstrap.Modal.getOrCreateInstance(modal).show()}))});</script>@endpush
@endsection
