@extends('layouts.admin')
@section('title','Downloads')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h4 mb-1">Downloads</h1><p class="text-muted mb-0">Publish private, public or paid resources.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createDownload"><i class="fas fa-plus me-1"></i> Create download</button></div>
@if(session('ok'))<div class="alert alert-success">{{ session('ok') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card"><div class="card-body"><form class="row g-2 mb-3"><div class="col"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Name or version"></div><div class="col"><select class="form-select" name="category_id"><option value="">All categories</option>@foreach($categories as $c)<option value="{{ $c->id }}" @selected(request('category_id')==$c->id)>{{ $c->name }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-outline-primary">Filter</button></div></form>
<div class="table-responsive"><table class="table table-striped align-middle"><thead><tr><th>Name</th><th>Category</th><th>Source</th><th>Visibility</th><th>Price</th><th>Downloads</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($downloads as $d) @php($downloadEditData=['name'=>$d->name,'source_type'=>$d->source_type,'version'=>$d->version,'external_url'=>$d->external_url,'description'=>$d->description,'download_category_id'=>$d->download_category_id,'visibility'=>$d->visibility,'price'=>$d->price,'expires_at'=>$d->expires_at?->format('Y-m-d\TH:i'),'active'=>$d->active,'original_name'=>$d->original_name])<tr><td><strong>{{ $d->name }}</strong><div class="small text-muted">{{ $d->version }}</div></td><td>{{ $d->category?->name ?: '—' }}</td><td>{{ ucfirst($d->source_type) }}</td><td><span class="badge text-bg-{{ $d->visibility==='paid'?'warning':($d->visibility==='public'?'success':'secondary') }}">{{ ucfirst($d->visibility) }}</span></td><td>{{ $d->visibility==='paid'?number_format((float)$d->price,2).' credits':'—' }}</td><td>{{ $d->download_count }}</td><td>{{ $d->active?'Active':'Inactive' }}</td><td class="text-nowrap"><a class="btn btn-sm btn-success" href="{{ route('admin.downloads.download',$d) }}" title="Download"><i class="fas fa-download"></i></a> <button class="btn btn-sm btn-warning js-edit-download" type="button" data-id="{{ $d->id }}" data-action="{{ route('admin.downloads.update',$d) }}" title="Edit"><i class="fas fa-pen"></i></button> <form class="d-inline" method="POST" action="{{ route('admin.downloads.destroy',$d) }}" onsubmit="return confirm('Delete this download?')">@csrf @method('DELETE')<button class="btn btn-sm btn-danger" title="Delete"><i class="fas fa-trash"></i></button></form><script type="application/json" id="downloadData{{ $d->id }}">{!! json_encode($downloadEditData, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) !!}</script></td></tr>
@empty<tr><td colspan="8" class="text-center text-muted py-5">No downloads.</td></tr>@endforelse
</tbody></table></div>{{ $downloads->links() }}</div></div>

<div class="modal fade" id="createDownload" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form method="POST" enctype="multipart/form-data" action="{{ route('admin.downloads.store') }}" class="modal-content download-form">@csrf<div class="modal-header bg-success text-white"><h2 class="modal-title h5">Create download</h2><button class="btn-close btn-close-white" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-12"><label class="form-label">Name</label><input class="form-control" name="name" required maxlength="150"></div><div class="col-md-6"><label class="form-label">Type</label><select class="form-select js-download-source" name="source_type"><option value="file">File</option><option value="external">External URL</option></select></div><div class="col-md-6"><label class="form-label">Version</label><input class="form-control" name="version"></div><div class="col-12 js-download-file"><label class="form-label">File</label><input class="form-control" type="file" name="file"></div><div class="col-12 d-none js-download-url"><label class="form-label">External URL</label><input class="form-control" type="url" name="external_url" placeholder="https://"></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control summernote" name="description" rows="9" data-editor="summernote" data-summernote-height="260" data-upload-url="{{ route('admin.uploads.summernote') }}"></textarea></div><div class="col-md-6"><label class="form-label">Category</label><select class="form-select" name="download_category_id"><option value="">No category</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Visibility</label><select class="form-select js-download-visibility" name="visibility"><option value="hidden">Hidden</option><option value="private">Private</option><option value="public" selected>Public</option><option value="paid">Paid</option></select></div><div class="col-md-6 d-none js-download-price"><label class="form-label">Price</label><div class="input-group"><input class="form-control" type="number" min="0.01" step="0.01" name="price"><span class="input-group-text">Credits</span></div></div><div class="col-md-6"><label class="form-label">Expires at</label><input class="form-control" type="datetime-local" name="expires_at"></div><div class="col-12"><input type="hidden" name="active" value="0"><div class="form-check form-switch"><input class="form-check-input" id="downloadActive" type="checkbox" name="active" value="1" checked><label class="form-check-label" for="downloadActive">Active</label></div></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button><button class="btn btn-success">Create</button></div></form></div></div>

<div class="modal fade" id="editDownload" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form method="POST" enctype="multipart/form-data" class="modal-content download-form" id="editDownloadForm">@csrf @method('PUT')<div class="modal-header bg-warning"><h2 class="modal-title h5">Edit download</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-12"><label class="form-label">Name</label><input class="form-control" name="name" required maxlength="150"></div><div class="col-md-6"><label class="form-label">Type</label><select class="form-select js-download-source" name="source_type"><option value="file">File</option><option value="external">External URL</option></select></div><div class="col-md-6"><label class="form-label">Version</label><input class="form-control" name="version"></div><div class="col-12 js-download-file"><label class="form-label">Replace file <small class="text-muted">(optional)</small></label><input class="form-control" type="file" name="file"><div class="form-text js-current-file"></div></div><div class="col-12 d-none js-download-url"><label class="form-label">External URL</label><input class="form-control" type="url" name="external_url" placeholder="https://"></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control summernote" name="description" rows="9" data-editor="summernote" data-summernote-height="260" data-upload-url="{{ route('admin.uploads.summernote') }}"></textarea></div><div class="col-md-6"><label class="form-label">Category</label><select class="form-select" name="download_category_id"><option value="">No category</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Visibility</label><select class="form-select js-download-visibility" name="visibility"><option value="hidden">Hidden</option><option value="private">Private</option><option value="public">Public</option><option value="paid">Paid</option></select></div><div class="col-md-6 d-none js-download-price"><label class="form-label">Price</label><div class="input-group"><input class="form-control" type="number" min="0.01" step="0.01" name="price"><span class="input-group-text">Credits</span></div></div><div class="col-md-6"><label class="form-label">Expires at</label><input class="form-control" type="datetime-local" name="expires_at"></div><div class="col-12"><input type="hidden" name="active" value="0"><div class="form-check form-switch"><input class="form-check-input" id="editDownloadActive" type="checkbox" name="active" value="1"><label class="form-check-label" for="editDownloadActive">Active</label></div></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button><button class="btn btn-warning"><i class="fas fa-save me-1"></i> Save changes</button></div></form></div></div>

@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const configure=form=>{const source=form.querySelector('.js-download-source'),visibility=form.querySelector('.js-download-visibility'),file=form.querySelector('.js-download-file'),url=form.querySelector('.js-download-url'),price=form.querySelector('.js-download-price');const sync=()=>{const external=source.value==='external';file.classList.toggle('d-none',external);url.classList.toggle('d-none',!external);price.classList.toggle('d-none',visibility.value!=='paid');price.querySelector('input').required=visibility.value==='paid'};source.addEventListener('change',sync);visibility.addEventListener('change',sync);sync()};document.querySelectorAll('.download-form').forEach(configure);const createModal=document.getElementById('createDownload'),editModal=document.getElementById('editDownload'),editForm=document.getElementById('editDownloadForm');createModal.addEventListener('shown.bs.modal',()=>window.initSummernoteIn?.(createModal),{once:true});editModal.addEventListener('shown.bs.modal',()=>window.initSummernoteIn?.(editModal),{once:true});document.querySelectorAll('.js-edit-download').forEach(button=>button.addEventListener('click',()=>{const data=JSON.parse(document.getElementById(`downloadData${button.dataset.id}`).textContent);editForm.action=button.dataset.action;editForm.querySelector('[name=name]').value=data.name||'';editForm.querySelector('[name=source_type]').value=data.source_type||'file';editForm.querySelector('[name=version]').value=data.version||'';editForm.querySelector('[name=external_url]').value=data.external_url||'';editForm.querySelector('[name=download_category_id]').value=data.download_category_id||'';editForm.querySelector('[name=visibility]').value=data.visibility||'public';editForm.querySelector('[name=price]').value=data.price||'';editForm.querySelector('[name=expires_at]').value=data.expires_at||'';editForm.querySelector('[name=active]').checked=Boolean(data.active);editForm.querySelector('.js-current-file').textContent=data.original_name?`Current file: ${data.original_name}`:'No file currently stored.';editForm.querySelector('[name=source_type]').dispatchEvent(new Event('change'));editForm.querySelector('[name=visibility]').dispatchEvent(new Event('change'));const description=editForm.querySelector('[name=description]');description.value=data.description||'';if(window.jQuery&&window.jQuery(description).next('.note-editor').length)window.jQuery(description).summernote('code',data.description||'');bootstrap.Modal.getOrCreateInstance(editModal).show()}))});</script>@endpush
@endsection
