@extends('layouts.customer')
@section('title','Account statement')
@section('content')
<div class="page-heading"><div><span class="eyebrow">FINANCE</span><h1>Account statement</h1><p>Every balance credit, purchase, order charge and refund in one place.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" target="_blank" href="{{ route('customer.payments.statement.print',request()->query()) }}"><i class="fas fa-print me-2"></i>Print</a><a class="btn btn-gsm" href="{{ route('customer.payments.create') }}">Add funds</a></div></div>
<form class="gsm-card p-3 mb-3"><div class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label small">From</label><input class="form-control" type="date" name="from" value="{{ request('from') }}"></div><div class="col-md-4"><label class="form-label small">To</label><input class="form-control" type="date" name="to" value="{{ request('to') }}"></div><div class="col-md-4"><button class="btn btn-outline-primary w-100">Apply filter</button></div></div></form>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="stat-card"><small>Opening balance</small><strong class="d-block h4 mt-2">${{ number_format((float)$opening,2) }}</strong></div></div><div class="col-md-3"><div class="stat-card"><small>Total credited</small><strong class="d-block h4 mt-2 text-success">+${{ number_format((float)$summary['income'],2) }}</strong></div></div><div class="col-md-3"><div class="stat-card"><small>Total spent</small><strong class="d-block h4 mt-2 text-danger">-${{ number_format((float)$summary['expense'],2) }}</strong></div></div><div class="col-md-3"><div class="stat-card"><small>Refunds</small><strong class="d-block h4 mt-2 text-primary">${{ number_format((float)$summary['refund'],2) }}</strong></div></div></div>
<div class="gsm-card p-3"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Date</th><th>Description</th><th>Reference</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>@forelse($transactions as $row)<tr><td class="text-nowrap">{{ $row->created_at->format('Y-m-d H:i') }}</td><td><strong>{{ $row->note ?: str($row->kind)->replace('_',' ')->title() }}</strong><div class="small text-muted">{{ str($row->kind)->replace('_',' ')->title() }}</div></td><td><code>{{ $row->reference ?: '—' }}</code></td><td class="text-danger fw-bold">{{ $row->direction==='expense'?'− $'.number_format((float)$row->amount,2):'—' }}</td><td class="text-success fw-bold">{{ $row->direction==='income'?'+ $'.number_format((float)$row->amount,2):'—' }}</td><td class="fw-bold">${{ number_format((float)$row->balance_after,2) }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">No account movements yet.</td></tr>@endforelse</tbody></table></div>{{ $transactions->links() }}</div>
<div class="mt-4"><h2 class="h5 fw-bold">Recent payment requests</h2><div class="gsm-card p-3"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Reference</th><th>Method</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>@forelse($payments as $row)<tr><td><a href="{{ route('customer.payments.show',$row) }}">{{ str($row->uuid)->limit(12) }}</a></td><td>{{ $row->gateway?->name ?? 'Historical method' }}</td><td>{{ $row->payable_currency }} {{ $row->currency_code }}</td><td><span class="status-pill status-{{ $row->status }}">{{ ucfirst($row->status) }}</span></td><td>{{ $row->created_at->format('Y-m-d H:i') }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No payment requests yet.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
