<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\Download;use App\Models\DownloadCategory;use App\Services\Content\HtmlSanitizer;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Illuminate\Validation\Rule;use Illuminate\Validation\ValidationException;
final class DownloadController extends Controller {
 private const BLOCKED=['php','php3','php4','php5','phtml','phar','cgi','pl','py','rb','sh','bash','exe','dll','com','bat','cmd','msi','js','html','htm','svg'];
 public function index(Request $r){$downloads=Download::query()->with('category')->withCount('logs')->when($r->filled('q'),fn($q)=>$q->where(fn($q)=>$q->where('name','like','%'.$r->string('q').'%')->orWhere('version','like','%'.$r->string('q').'%')))->when($r->filled('category_id'),fn($q)=>$q->where('download_category_id',$r->integer('category_id')))->orderByDesc('id')->paginate(25)->withQueryString();$categories=DownloadCategory::query()->where('active',true)->orderBy('ordering')->get();return view('admin.downloads.index',compact('downloads','categories'));}
 public function store(Request $r):RedirectResponse{$d=$this->data($r);$this->guardFile($r);DB::transaction(function()use($r,$d){$download=Download::create($this->storeFile($r,$d));$download->users()->sync($r->input('allowed_user_ids',[]));$download->groups()->sync($r->input('allowed_group_ids',[]));});return back()->with('ok','Download created.');}
 public function update(Request $r,Download $download):RedirectResponse{$d=$this->data($r,true);$this->guardFile($r);$old=$download->storage_path;DB::transaction(function()use($r,$d,$download){$download->update($this->storeFile($r,$d,$download));$download->users()->sync($r->input('allowed_user_ids',[]));$download->groups()->sync($r->input('allowed_group_ids',[]));});if($r->hasFile('file')&&$old&&$old!==$download->storage_path)Storage::disk('local')->delete($old);return back()->with('ok','Download updated.');}
 public function destroy(Download $download):RedirectResponse{$path=$download->storage_path;$download->delete();if($path)Storage::disk('local')->delete($path);return back()->with('ok','Download deleted.');}
 public function deliver(Request $r,Download $download){$this->authorizeDelivery($r,$download);DB::transaction(function()use($download,$r){Download::query()->whereKey($download->id)->increment('download_count');$download->logs()->create(['user_id'=>$r->user()?->id,'ip_hash'=>hash('sha256',(string)$r->ip().config('app.key')),'user_agent_hash'=>hash('sha256',(string)$r->userAgent()),'downloaded_at'=>now()]);});if($download->source_type==='external')return redirect()->away($download->external_url);abort_unless($download->storage_path&&Storage::disk('local')->exists($download->storage_path),404);return Storage::disk('local')->download($download->storage_path,$download->original_name?:basename($download->storage_path),['Content-Type'=>$download->mime_type?:'application/octet-stream','X-Content-Type-Options'=>'nosniff']);}
 private function data(Request $r,bool $update=false):array{$r->mergeIfMissing(['visibility'=>'public']);$d=$r->validate(['name'=>'required|string|max:150','description'=>'nullable|string|max:20000','download_category_id'=>'nullable|exists:download_categories,id','source_type'=>['required',Rule::in(['file','external'])],'file'=>[$update?'nullable':'required_if:source_type,file','file','max:102400'],'external_url'=>'nullable|required_if:source_type,external|url:http,https|max:2048','version'=>'nullable|string|max:50','active'=>'nullable|boolean','visibility'=>['required',Rule::in(['hidden','private','public','paid'])],'price'=>'nullable|required_if:visibility,paid|decimal:0,2|min:0.01|max:99999999','expires_at'=>'nullable|date','allowed_user_ids'=>'nullable|array|max:500','allowed_user_ids.*'=>'integer|distinct|exists:users,id','allowed_group_ids'=>'nullable|array|max:500','allowed_group_ids.*'=>'integer|distinct|exists:groups,id']);$d['description']=app(HtmlSanitizer::class)->clean($d['description']??'');$d['price']=$d['visibility']==='paid'?(string)$d['price']:'0';return $d;}
 private function guardFile(Request $r):void{if(!$r->hasFile('file'))return;$file=$r->file('file');$ext=strtolower($file->getClientOriginalExtension());if(in_array($ext,self::BLOCKED,true)||str_contains(strtolower($file->getClientOriginalName()),'.php'))throw ValidationException::withMessages(['file'=>'Executable or browser-active files are not allowed.']);}
 private function storeFile(Request $r,array $d,?Download $download=null):array{$d['active']=$r->boolean('active');$d['is_free']=$d['visibility']!=='paid';if(!Schema::hasColumn('downloads','visibility'))unset($d['visibility'],$d['price']);if($d['source_type']==='external'){$d['storage_path']=$d['original_name']=$d['mime_type']=$d['size']=null;}elseif($r->hasFile('file')){$file=$r->file('file');$ext=strtolower($file->getClientOriginalExtension())?:'bin';$d['storage_path']=$file->storeAs('downloads',Str::uuid().'.'.$ext,'local');$d['original_name']=$file->getClientOriginalName();$d['mime_type']=$file->getMimeType();$d['size']=$file->getSize();$d['external_url']=null;}else{foreach(['storage_path','original_name','mime_type','size'] as $key)$d[$key]=$download?->$key;$d['external_url']=null;}return $d;}
 private function authorizeDelivery(Request $r,Download $d):void{$d->loadMissing('category');abort_unless($d->active&&(!$d->expires_at||$d->expires_at->isFuture()),404);$u=$r->user();abort_unless($u,403);if($u->hasRole('Administrator'))return;$permission=$d->category?->required_permission;if($permission){try{abort_unless($u->can($permission),403);}catch(\Throwable){abort(403);}}$userRestricted=DB::table('download_user')->where('download_id',$d->id)->exists();$groupRestricted=DB::table('download_group')->where('download_id',$d->id)->exists();$userAllowed=DB::table('download_user')->where('download_id',$d->id)->where('user_id',$u->id)->exists();$groupAllowed=$u->group_id&&DB::table('download_group')->where('download_id',$d->id)->where('group_id',$u->group_id)->exists();if($userRestricted||$groupRestricted)abort_unless($userAllowed||$groupAllowed,403);}
}
