<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\Setting;use Illuminate\Http\Request;use Illuminate\Support\Facades\Artisan;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\File;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
final class SystemController extends Controller{
 private const IMAGE_EXTENSIONS=['jpg','jpeg','png','webp','gif','avif'];
 private const CUSTOMER_UPLOADS=['proof','proofs','receipt','receipts','payment-proofs','payment_proofs'];
 public function files(){
  $files=collect(Storage::disk('public')->allFiles())->filter(function($path){$lower=strtolower($path);return in_array(pathinfo($lower,PATHINFO_EXTENSION),self::IMAGE_EXTENSIONS,true)&&!collect(self::CUSTOMER_UPLOADS)->contains(fn($folder)=>str_contains($lower,$folder));})->map(fn($p)=>['path'=>$p,'name'=>basename($p),'folder'=>dirname($p)==='.'?'Root':dirname($p),'size'=>Storage::disk('public')->size($p),'modified'=>Storage::disk('public')->lastModified($p),'url'=>Storage::disk('public')->url($p),'managed'=>str_starts_with($p,'admin-media/')])->sortByDesc('modified')->values();
  return view('admin.system.files',compact('files'));
 }
 public function upload(Request $r){$r->validate(['file'=>'required|image|mimes:jpg,jpeg,png,webp,gif,avif|max:10240']);$f=$r->file('file');$f->storeAs('admin-media',Str::uuid().'.'.strtolower($f->getClientOriginalExtension()),'public');return back()->with('ok','Image uploaded and added to the media library.');}
 public function download(string $name){$name=basename($name);$path=collect(Storage::disk('public')->allFiles())->first(fn($p)=>basename($p)===$name&&in_array(strtolower(pathinfo($p,PATHINFO_EXTENSION)),self::IMAGE_EXTENSIONS,true));abort_unless($path,404);return Storage::disk('public')->download($path);}
 public function delete(string $name){$name=basename($name);$path=collect(Storage::disk('public')->files('admin-media'))->first(fn($p)=>basename($p)===$name);abort_unless($path,404);Storage::disk('public')->delete($path);return back()->with('ok','Media image deleted.');}
 public function maintenance(){return view('admin.system.maintenance',['enabled'=>Setting::where('setting_key','system.maintenance')->value('value')==='1','message'=>Setting::where('setting_key','system.maintenance_message')->value('value'),'image'=>Setting::where('setting_key','system.maintenance_image')->value('value')]);}
 public function maintenanceUpdate(Request $r){$data=$r->validate(['enabled'=>'required|boolean','message'=>'nullable|string|max:5000','image'=>'nullable|image|mimes:jpg,jpeg,png,webp,gif,avif|max:10240','remove_image'=>'nullable|boolean']);$current=Setting::where('setting_key','system.maintenance_image')->value('value');if($r->boolean('remove_image')&&$current){Storage::disk('public')->delete($current);$current=null;}if($r->hasFile('image')){if($current)Storage::disk('public')->delete($current);$current=$r->file('image')->store('maintenance','public');}foreach(['system.maintenance'=>[$r->boolean('enabled')?'1':'0','boolean'],'system.maintenance_message'=>[$data['message']??null,'string'],'system.maintenance_image'=>[$current,'string']] as $key=>[$value,$type])Setting::updateOrCreate(['setting_key'=>$key],['group_name'=>'system','value'=>$value,'value_type'=>$type,'is_encrypted'=>false]);return back()->with('ok','Customer maintenance page updated.');}
 public function backups(){return view('admin.system.backups',['files'=>collect(Storage::disk('local')->files('backups'))->map(fn($p)=>['name'=>basename($p),'size'=>Storage::disk('local')->size($p),'modified'=>Storage::disk('local')->lastModified($p)])]);}
 public function backupCreate(){set_time_limit(120);$driver=DB::getDriverName();if($driver==='sqlite'){$tables=collect(DB::select("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"))->pluck('name');}elseif(in_array($driver,['mysql','mariadb'],true)){$tables=collect(DB::select('SHOW TABLES'))->map(fn($r)=>array_values((array)$r)[0]);}else{throw ValidationException::withMessages(['backup'=>'Database backups are not supported for the configured driver: '.$driver]);}$data=['created_at'=>now()->toIso8601String(),'driver'=>$driver,'tables'=>[]];foreach($tables as $table){if(!preg_match('/^[A-Za-z0-9_]+$/',$table))continue;$data['tables'][$table]=DB::table($table)->get()->map(fn($r)=>(array)$r)->all();}$name='backup-'.now()->format('Ymd-His').'-'.Str::random(8).'.enc';Storage::disk('local')->put('backups/'.$name,Crypt::encryptString(json_encode($data,JSON_THROW_ON_ERROR)));return back()->with('ok','Encrypted database backup created.');}
 public function backupDownload(string $name){$name=basename($name);$path='backups/'.$name;abort_unless(str_ends_with($name,'.enc')&&Storage::disk('local')->exists($path),404);return Storage::disk('local')->download($path);}
 public function backupDelete(string $name){$name=basename($name);abort_unless(str_ends_with($name,'.enc'),404);Storage::disk('local')->delete('backups/'.$name);return back()->with('ok','Backup deleted.');}
 public function update(){return view('admin.system.update',['php'=>PHP_VERSION,'laravel'=>app()->version(),'commit'=>trim((string)shell_exec('git rev-parse --short HEAD 2>/dev/null'))]);}
 public function clearCaches(){Artisan::call('optimize:clear');return back()->with('ok','Application caches cleared. No package or migration was executed.');}
}
