<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\Setting;use Illuminate\Http\Request;use Illuminate\Support\Facades\Artisan;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\File;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
final class SystemController extends Controller{
 private const ROOT='system-files';private const BLOCKED=['php','phtml','phar','cgi','pl','py','rb','sh','exe','dll','bat','cmd','js','html','svg'];
 public function files(){return view('admin.system.files',['files'=>collect(Storage::disk('local')->files(self::ROOT))->map(fn($p)=>['path'=>$p,'name'=>basename($p),'size'=>Storage::disk('local')->size($p),'modified'=>Storage::disk('local')->lastModified($p)])]);}
 public function upload(Request $r){$r->validate(['file'=>'required|file|max:51200']);$f=$r->file('file');$ext=strtolower($f->getClientOriginalExtension());if(in_array($ext,self::BLOCKED,true)||str_contains(strtolower($f->getClientOriginalName()),'.php'))throw ValidationException::withMessages(['file'=>'Executable files are forbidden.']);$f->storeAs(self::ROOT,Str::uuid().'.'.($ext?:'bin'),'local');return back()->with('ok','File uploaded to private storage.');}
 public function download(string $name){$name=basename($name);$path=collect(Storage::disk('local')->files(self::ROOT))->first(fn($p)=>basename($p)===$name);abort_unless($path,404);return Storage::disk('local')->download($path);}
 public function delete(string $name){$name=basename($name);$path=collect(Storage::disk('local')->files(self::ROOT))->first(fn($p)=>basename($p)===$name);abort_unless($path,404);Storage::disk('local')->delete($path);return back()->with('ok','File deleted.');}
 public function maintenance(){return view('admin.system.maintenance',['enabled'=>(bool)optional(Setting::where('setting_key','system.maintenance')->first())->value]);}
 public function maintenanceUpdate(Request $r){$r->validate(['enabled'=>'required|boolean','message'=>'nullable|string|max:1000']);Setting::updateOrCreate(['setting_key'=>'system.maintenance'],['group_name'=>'system','value'=>$r->boolean('enabled')?'1':'0','value_type'=>'boolean','is_encrypted'=>false]);Setting::updateOrCreate(['setting_key'=>'system.maintenance_message'],['group_name'=>'system','value'=>$r->input('message'),'value_type'=>'string','is_encrypted'=>false]);return back()->with('ok','Maintenance setting updated.');}
 public function backups(){return view('admin.system.backups',['files'=>collect(Storage::disk('local')->files('backups'))->map(fn($p)=>['name'=>basename($p),'size'=>Storage::disk('local')->size($p),'modified'=>Storage::disk('local')->lastModified($p)])]);}
 public function backupCreate(){set_time_limit(120);$tables=collect(DB::select("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"))->pluck('name');if(DB::getDriverName()!=='sqlite')$tables=collect(DB::select('SHOW TABLES'))->map(fn($r)=>array_values((array)$r)[0]);$data=['created_at'=>now()->toIso8601String(),'driver'=>DB::getDriverName(),'tables'=>[]];foreach($tables as $table){if(!preg_match('/^[A-Za-z0-9_]+$/',$table))continue;$data['tables'][$table]=DB::table($table)->get()->map(fn($r)=>(array)$r)->all();}$name='backup-'.now()->format('Ymd-His').'-'.Str::random(8).'.enc';Storage::disk('local')->put('backups/'.$name,Crypt::encryptString(json_encode($data,JSON_THROW_ON_ERROR)));return back()->with('ok','Encrypted database backup created.');}
 public function backupDownload(string $name){$name=basename($name);$path='backups/'.$name;abort_unless(str_ends_with($name,'.enc')&&Storage::disk('local')->exists($path),404);return Storage::disk('local')->download($path);}
 public function backupDelete(string $name){$name=basename($name);abort_unless(str_ends_with($name,'.enc'),404);Storage::disk('local')->delete('backups/'.$name);return back()->with('ok','Backup deleted.');}
 public function update(){return view('admin.system.update',['php'=>PHP_VERSION,'laravel'=>app()->version(),'commit'=>trim((string)shell_exec('git rev-parse --short HEAD 2>/dev/null'))]);}
 public function clearCaches(){Artisan::call('optimize:clear');return back()->with('ok','Application caches cleared. No package or migration was executed.');}
}
