@php($prefix = $currency ? 'edit_'.$currency->id.'_' : '')
<div class="row g-3">
  <div class="col-md-3"><label class="form-label">ISO code</label><input name="code" required minlength="3" maxlength="3" class="form-control text-uppercase" placeholder="USD" value="{{ $currency?->code }}"></div>
  <div class="col-md-5"><label class="form-label">Name</label><input name="name" required maxlength="100" class="form-control" value="{{ $currency?->name }}"></div>
  <div class="col-md-4"><label class="form-label">Symbol</label><input name="symbol" required maxlength="10" class="form-control" value="{{ $currency?->symbol }}"></div>
  <div class="col-md-6"><label class="form-label">Exchange rate</label><input type="number" step="0.00000001" min="0.00000001" name="exchange_rate" required class="form-control" value="{{ $currency?->exchange_rate ?? '1.00000000' }}" @readonly($currency?->is_default)></div>
  <div class="col-md-3"><label class="form-label">Decimal places</label><input type="number" min="0" max="8" name="decimal_places" required class="form-control" value="{{ $currency?->decimal_places ?? 2 }}"></div>
  <div class="col-md-3"><label class="form-label">Symbol position</label><select name="symbol_position" class="form-select"><option value="before" @selected(($currency?->symbol_position ?? 'before') === 'before')>Before</option><option value="after" @selected($currency?->symbol_position === 'after')>After</option></select></div>
  <div class="col-md-4"><label class="form-label">Decimal separator</label><select name="decimal_separator" class="form-select"><option value="." @selected(($currency?->decimal_separator ?? '.') === '.')>Dot (.)</option><option value="," @selected($currency?->decimal_separator === ',')>Comma (,)</option></select></div>
  <div class="col-md-4"><label class="form-label">Thousands separator</label><select name="thousands_separator" class="form-select"><option value="," @selected(($currency?->thousands_separator ?? ',') === ',')>Comma (,)</option><option value="." @selected($currency?->thousands_separator === '.')>Dot (.)</option><option value=" " @selected($currency?->thousands_separator === ' ')>Space</option><option value="'" @selected($currency?->thousands_separator === "'")>Apostrophe</option></select></div>
  <div class="col-md-4"><label class="form-label">Ordering</label><input type="number" min="0" name="ordering" class="form-control" value="{{ $currency?->ordering ?? 0 }}"></div>
  <div class="col-6"><input type="hidden" name="active" value="0"><div class="form-check form-switch"><input class="form-check-input" id="{{ $prefix }}currencyActive" type="checkbox" name="active" value="1" @checked($currency?->active ?? true)><label class="form-check-label" for="{{ $prefix }}currencyActive">Active</label></div></div>
  <div class="col-6"><input type="hidden" name="is_default" value="0"><div class="form-check form-switch"><input class="form-check-input" id="{{ $prefix }}currencyDefault" type="checkbox" name="is_default" value="1" @checked($currency?->is_default ?? false)><label class="form-check-label" for="{{ $prefix }}currencyDefault">Default currency</label></div></div>
</div>
